### ISSUE TITLE
backend error when trying to call java method named "hash"

### ISSUE THREAD

**Issue by fgutmann** [ceylon/ceylon-compiler#1383]
I'm trying to use the [guava Hasher](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/hash/Hasher.html) to gernate an sha1 hash.

The method to generate the hash is called `hash` which somewhat conflicts with the ceylon hash attribute. Whether I'm trying to rename the method during the import or not, it always results in a backend error "[Backend error] cannot find symbol symbol: method asBytes() location: class java.lang.Integer".

The backend probably tries to execute the hashCode() java method which returns an `Integer` instead of the desired `HashResult`.

Here is some code to reproduce:

```
import com.google.common.hash {
    Hashing { sha1 },
    Hasher { hashIt = hash }
}

void run() { 
    Hasher hasher = sha1().newHasher();
    hasher.putInt(12345);
    value bytesA = hasher.hash().asBytes(); // [Backend error]
    value bytesB = hasher.hashIt().asBytes(); // [Backend error]
}
```

**Comment by FroMage** [comment]
I've amended this in ceylon/ceylon.language#670 to properly mark `hash`/`string` attributes variable if there is a setter but no getter, as this could happen with pure Ceylon code.
