### ISSUE TITLE
Removing a source file from a module will leave its classes in the CAR

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-compiler#1396]
If you compile a module, then remove one of its sources files and compile it again (assuming that removing the file did not result in errors) the resulting CAR will still contain the class files that belong to the now removed source file.

The problem here is that pretty early on during compilation the module name that was given on the command line gets "expanded" into the list of it's component source files. When we get to the point where the CAR file gets created or updated we don't know if we're compiling the entire module (which would suggest starting fresh) or just parts of it (and only update the changed files like we do now).

**Comment by luolong** [comment]
Simple intuition says that generally you don't switch those sources willy-nilly on every compilation. Usually, there is a reason why you add (or remove) a source folder and you do not do compilations every time with a different set of sources. Specially if I compile from command line.

If I call the command line compiler with a new set of source folders, I assume, that there is a different result I want to achieve and if that means some of the classes get removed from the module car file, I am totally fine with it.

The way I see it, if after combining the source folders, the resulting source path fileset does not contain a source file that existed before, it can be considered deleted and thus can be safely removed from the .car file.

**Comment by quintesse** [comment]
@luolong No, that exactly *not* what we want. This behaviour has been implemented (and used in the SDK before we had `native`) especially to be able to build code that otherwise can't be built using a single invocation of the compiler. So as this issue already explained and states `WONTFIX`.
