### ISSUE TITLE
annotating fields

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#1471]
Our Java annotation interoperability doesn't let you annotate fields of a class: annotations get applied to the getter method.

Doing the "right thing" when the annotation type's target element includes FIELD but not METHOD would probably get us most of the way there, though there will be cases where the target elements includes both, and it matters to the annotation consumer.

**Comment by jvasileff** [comment]
+1! The inability to annotate unnamed constructors, fields, and generated setters results in a workaround that leaves Ceylon classes looking like java beans!

Ceylon does seem like it will be particularly well suited for this:

```ceylon
late resource Sql sql;
```

**Comment by jvasileff** [comment]
It looks like annotations will need to be made on the generated setters, not fields, since setters are responsible for marking fields as initialized (`this.$init$myField = true;`) for `late` references.

An issue that might come up is confusing injection errors due to name mangling of the setters (`setMyField$priv$(...)`), breaking Java Bean conventions. But maybe documentation is enough for this.

**Comment by jvasileff** [comment]
On the other hand, there are JSR 303 (javax.validation) constraint annotations that support both ``METHOD`` and ``FIELD`` that should not be applied to setters.

**Comment by tombentley** [comment]
I was going to add warnings to all those usages of interop annotations which would be ambiguous, but it turns out that the `WarningSuppressionVisitor` runs during `analyseUsage()` as part of typechecking and thus before the `UnsupportedVisitor` (or any of the other code generator visitors), which would mean such warnings wouldn't respect `suppressWarnings`. I guess I should move it to run immediately before we go printing the error to the compiler log.

**Comment by tombentley** [comment]
This should now be fixed. 

When we synthesize the ceylon annotation constructor `annotationType` for a Java `@AnnotationType` which can target multiple annotations we now also snythesize `annotationType__CONSTRUCTOR`, `annotationType__FIELD` etc (according to the `@Target`).

Use of `annotationType` in unambiguous places works as before. In ambiguous places it works as before, but with a warning that it's ambiguous (which you can get rid of by using the unambiguous annotation constructor instead).

If people can agree on a better naming scheme than `annotationType__CONSTRUCTOR` then I'm happy to implement that.

**Comment by tombentley** [comment]
Oh, it's possible I missed a few corner cases in the call sites, such that a Java element won't get annotated despite the Ceylon element having an unambiguous annotation. Please open a new issue if you find such omissions.

**Comment by FroMage** [comment]
> If people can agree on a better naming scheme than `annotationType__CONSTRUCTOR` then I'm happy to implement that.

Yes, I find that a bit harsh and cryptic, a better name would obviously be `annotationType__pleasePutThisOnTheConstrustructorKThanksTom`.

**Comment by tombentley** [comment]
Yeah, lowercasing the enumeration constant would make it look a bit less jarring, and I almost wonder about using a single `_` too.

**Comment by jvasileff** [comment]
I just tried this out, works great.

Would it be possible to add `_SETTER` as well, as in:

```ceylon
late inject__SETTER Sql sql;
```
Since METHOD is still ambiguous here.

**Comment by jvasileff** [comment]
Just brainstorming, but what about `\iConstructorAnnotationType`?

**Comment by tombentley** [comment]
> Would it be possible to add `_SETTER` as well?

*Possibly*, could you open a separate issue for that.
