### ISSUE TITLE
ceylon help should page output

### ISSUE THREAD

**Issue by hnridder** [ceylon/ceylon-compiler#1506]
When running ceylon help the output is sparsely formatted (indented, but no attributes) and not paged. I suggest to use man(1) to display the output formatted & paged, or alternatively, pipe the formatted output through $PAGER.

**Comment by FroMage** [comment]
HAHA! It's not done in a shell script. It's done in C by spawning a pager program and piping stdout to it. We can do the same in Java by setting `System.out` (or just printing the help to a special pager stream) and we won't have issues with parsing the help flag :)

**Comment by FroMage** [comment]
https://github.com/git/git/blob/fbecd99861ea5795aeba46faf2ac7a8c1b70d485/pager.c for info

**Comment by quintesse** [comment]
> We can do the same in Java by setting System.out

I'm not sure I understand, so who would do the paging?

**Comment by FroMage** [comment]
`less`, but it's started from Java where we already know how to parse the `--help` flag.

**Comment by quintesse** [comment]
Ah ok, so you start the pager from within the program and then pipe the output to it. Sounds easy enough. And like they do in the git helper, look at `CEYLON_PAGER` first, then at the default Linux (Unix?) `PAGER` and finally using `less`. And maybe some option to disable paging? (So you won't have to do `PAGER=cat ceylon foo --help`)

**Comment by FroMage** [comment]
Done and pushed. Please try it out, especially on Windows :)

**Comment by quintesse** [comment]
I think you forgot to push `ceylon-js`, but I fixed it already.

**Comment by quintesse** [comment]
Works great on Linux, but on Windows it doesn't show anything at all (unless I add the `--no-pager` flag).

**Comment by quintesse** [comment]
Works fine on Linux but doesn't work on Windows, neither in Git Bash (which simulates a unix-like environment) nor in the standard Windows command line. First because `less` doesn't exist in Windows but even when changing it to `more` it doesn't work and I guess this is because `more` is part of the Windows command "shell", so it's not a program that can be started.

**Comment by FroMage** [comment]
Damn, sorry about the missing push of `ceylon-js`.

**Comment by FroMage** [comment]
So, I tried to figure out what git does on Windows but it's not clear. Apparelty on Windows they have two strategies: one for using `sh -c` and the other using _native windows_ calls like `mingw_spawnvpe`. Can we really start a Windows command shell with `sh -c` on Windows?

**Comment by FroMage** [comment]
Wow, reading back C files I can say I'm glad I didn't write C code in the last seven years, that stuff is nuts.

**Comment by quintesse** [comment]
> Can we really start a Windows command shell with sh -c on Windows?

No, to me that sounds that they only take into account unix-like environments like MinGW.

Better yet, I just tested Git on Windows and it doesn't do paging at all... it... spawns an HTML page in a browser!

**Comment by FroMage** [comment]
Of course, my Windows drive is dead so I can't test any of this shit anymore :(

**Comment by FroMage** [comment]
Well, no idea then. I haven't found the code that does this in git.

**Comment by quintesse** [comment]
Well we do generate HTML docs for the distribution so we could go Git's way and spawn a browser and just forget about paging on Windows.

**Comment by quintesse** [comment]
And using `--no-pager` could still give us the current behaviour, in case someone want to, I don't know, pipe the help text somewhere.

**Comment by quintesse** [comment]
Btw, Git only seems to do this for *some* commands though. `git help checkout` shows the HTML page for `checkout`, but `git help` shows the list of all Git commands in the console (unpaged).

**Comment by quintesse** [comment]
Also, on Windows the `-paginate` and `--no-pager` options are completely ignored. You can't set a different pager and you can't disable paging.

**Comment by FroMage** [comment]
I just don't see it. Apparently they have different code paths for Windows and for Cygwin, but both would call `sh -c more`. I don't see where this browser behaviour is coming from.

**Comment by FroMage** [comment]
I don't find anything about piping to the browser in the code for git, so I don't know how they do it. I'm tempted to just disable paging by default on Windows. Also I can't test because my Windows drive is dead.

**Comment by quintesse** [comment]
They don't pipe (I don't even think that's possible with browsers), they just start the browser pointing to the local HTML doc page : `file:///C:/Program%20Files%20(x86)/Git/doc/git/html/git-checkout.html`

**Comment by FroMage** [comment]
OK but I don't even know how to start a browser.

**Comment by quintesse** [comment]
You can just "execute" the link and Windows will open the default browser for you. But the thing is how to get the URL?

**Comment by FroMage** [comment]
Seriously? Just execute a link?

**Comment by quintesse** [comment]
Yes, although maybe better to use `start`, eg `start file:///C:/Program%20Files%20(x86)/Git/doc/git/html/git-checkout.html` , that would probably work both in a regular CMD box and in a Cygwin shell.

**Comment by FroMage** [comment]
I pushed a fix for Windows, can you try it please?

**Comment by quintesse** [comment]
Fixed NPE and added a fall-back to the console if the docs weren't found. Works perfectly now!

**Comment by FroMage** [comment]
OK, so we can close this?

**Comment by quintesse** [comment]
Yup

**Comment by FroMage** [comment]
Thanks
