### ISSUE TITLE
Double error on dynamic block

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#1773]
``` ceylon
shared void run() {
    dynamic {
    }
}
```

> source/tmp/run.ceylon:2: error: dynamic is not yet supported on this platform
> 
> ``` ceylon
>     dynamic {
>    ^
> ```
> 
> source/tmp/run.ceylon:2: error: dynamic is not yet supported on this platform
> 
> ``` ceylon
>     dynamic {
>    ^
> ```
> 
> 2 errors

For some reason, you get the exact same error twice.

**Comment by taiar** [comment]
Is this already on 1.1.0? Because I have the same problem here.
