### ISSUE TITLE
Ceylon copy adds sha1 to module.xml

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#1848]
I'm not sure if the CMR even validates it. Should I support it in Herd or should we stop generating it in `ceylon copy`?

**Comment by FroMage** [comment]
@alesj any idea which direction we should head?

**Comment by quintesse** [comment]
@alesj ? Any comment?

**Comment by alesj** [comment]
// by default we don't check sha1 on remote nodes, it should be done after download
        if (context.isIgnoreSHA() == false && node.isRemote() == false && node.hasBinaries()) {

See comment -- it looked like a good idea at that time.
But we can change this to always check.

**Comment by quintesse** [comment]
Ok, I just debugged it and I see that it checks downloaded artifacts here: https://github.com/ceylon/ceylon-module-resolver/blob/master/impl/src/main/java/com/redhat/ceylon/cmr/impl/RootRepositoryManager.java#L199 when it stores them in the cache.

So I think we can close this issue as correct @FroMage . When we upload binaries to the HErd we can include the SHA1 so the Herd can check them (if it wants) and when we download them they get checked again the moment they get stored in the cache and on each local access thereafter.

**Comment by quintesse** [comment]
Oh wait, the issue title talks about `module.xml`, sorry. I had forgotten about that part.
Well, the CMR doesn't distinguish really between binary artifacts and textual ones and textual ones supposedly could contain errors too, so I don't know, can't hurt, can it?

Btw, I've just noticed that the CMR checks SHA1s when it downloads the artifact but then it doesn't store it alongside the downloaded item, we should probably do that.

**Comment by quintesse** [comment]
Ok, after checking some more the CMR does indeed **not** validate the SHA1 of any descriptors, even if they exist. Descriptor files are handled separately (https://github.com/ceylon/ceylon-module-resolver/blob/master/impl/src/main/java/com/redhat/ceylon/cmr/impl/RootRepositoryManager.java#L223)

**Comment by quintesse** [comment]
Ok, `ceylon copy` won't generate & copy SHA1s anymore for module descriptors. Closing.
