### ISSUE TITLE
Add tests to test the samples

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#1853]
Compile, run, doc, whatever.

**Comment by FroMage** [comment]
@quintesse do you mind taking those?

**Comment by quintesse** [comment]
I'm afraid I don't really understand the issue "tests to test the samples"?

**Comment by FroMage** [comment]
Make sure we can compile, run doc them. The samples we ship with.

**Comment by quintesse** [comment]
Ah, those samples! Sure.

**Comment by quintesse** [comment]
Seemed we were already doing this for the `helloworld` sample, I added the other 3 as well.

**Comment by FroMage** [comment]
Thanks!
