### ISSUE TITLE
`ceylon doc` tries to resolve dependencies of test module but fails even if `ceylon compile` works

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-compiler#1862]
To reproduce:
* create a module `abc.def` under directory `source`
* create a directory `test` with package `abc.def`.
* in `source/abc/def/module.ceylon`, declare a dependency such as `ceylon.test`.
* in `test/abc/def/`, add some test (using ceylon.test functions).
* compile with `ceylon compile abc.def`. Should work.
* generate docs with `ceylon doc abc.def`. Will complain that cannot find any `ceylon.test` symbols.

**Comment by quintesse** [comment]
@renatoathaydes Can you still reproduce this? Because I wasn't able to given your instructions.

**Comment by renatoathaydes** [comment]
I have not tested this in a long time.... if you can't reproduce, then we may assume it's gone now. Do you want me to try to reproduce later? (pretty busy now, otherwise would do it right away)...

**Comment by quintesse** [comment]
Ok, I'll close for now then. If you **want** you can try later and reopen if you get a different result than me.
