### ISSUE TITLE
Overriding method PB with spread/sequential arg and mutually-referring generic interfaces 

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#1875]
Compiling the following code:
``` ceylon
shared interface N<out ActualP, ActualN> 
        given ActualN satisfies N<ActualP, ActualN> 
{}

shared interface P<ActualN>
        given ActualN  satisfies N <P<ActualN>, ActualN>
{
    shared formal void f0(String * args);
    //shared formal void f1([String *] args);
}

shared class ConcreteN() satisfies N<ConcreteP, ConcreteN> {} 

shared class ConcreteP() satisfies P<ConcreteN> {
    shared actual void f0(String * p) {}
    //shared actual void f1([String *] p) {}
}
```
fails:
```
error: ConcreteP is not abstract and does not override abstract method f0(Sequential) in P
1 error
Note: Created module bug.override/1.0.0
ceylon compile: There was 1 error
```
Same kind of PB when `f1` is uncommented.

**Comment by tombentley** [comment]
@FroMage are you working on this?

**Comment by FroMage** [comment]
No I'm not.

**Comment by tombentley** [comment]
Fixed.

**Comment by FroMage** [comment]
I wonder if this is costly or not. I looks like it is. Can you measure time/memory difference between with or without this fix? If it is costly we should remember this info on the model annotations for a type.

**Comment by tombentley** [comment]
I can certainly measure the time difference. But having this information in the model doesn't really help because we'd still need to figure the same thing when confronted with declarations loaded from source.

**Comment by FroMage** [comment]
But that's what we do with the boxing visitors.

**Comment by tombentley** [comment]
Well for my trial runs it actually went faster *after* these patches and memory usage appeared very similar.

**Comment by FroMage** [comment]
Did you run the concurrent tests? If there's no difference then fine.

**Comment by tombentley** [comment]
Yes, the concurrent tests.

**Comment by FroMage** [comment]
OK then fine, great.
