### ISSUE TITLE
Cannot import jar which uses JDK

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#1876]
Trying to `import-jar` the servlet jar gives me:

```
The following JDK modules need to be declared as shared imports:
    java.base
ceylon import-jar: Problems were found, aborting.
```

I don't think that's right, because IMO every jar should import and share all of the java JDK. Things that come from Maven should, certainly because the JDK deps will not be declared. We can detect which bits of the JDK should be declared shared in `import-jar`, but I'm not sure it's useful.

**Comment by quintesse** [comment]
Turned the message into something informative only. Closing.
