### ISSUE TITLE
`ceylon import-jar` fails with complaint about java.base not being declared shared

### ISSUE THREAD

**Issue by tobias** [ceylon/ceylon-compiler#1902]
When trying to import a jar to create the javax.servlet module, I get:

    The following JDK modules need to be declared as shared imports:
        java.base
    ceylon import-jar: Problems were found, aborting.

This was with 1.1.0 and 1.1.1 (HEAD), with the following command:

    ceylon import-jar --out https://modules.ceylon-lang.org/uploads/6547/repo/ --user XXX --pass YYY javax.servlet/3.1.0 javax.servlet-api-3.1.0.jar

**Comment by quintesse** [comment]
@tobias Better this way? Closing.

**Comment by tobias** [comment]
Much better, thanks!
