### ISSUE TITLE
Backend error in IDE for incomplete class definition used at top level

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#1933]
This code, at top level in a ceylon source file :
```ceylon
class Foo
Foo f = Foo();
```
When compiled with the IDE :

```
The Ceylon Java backend compiler failed abnormally
```
And in the same vein, also at top level

```ceylon
interface Foo
Foo a = object satisfies Foo{};
```

**Comment by FroMage** [comment]
@davidfestal can you look at this please? If we need to reopen as an IDE issue I can do this.

**Comment by davidfestal** [comment]
Yes, I'll try to do this today, as soon as I've pushed my last IntelliJ changes

**Comment by FroMage** [comment]
Thanks.

**Comment by davidfestal** [comment]
Done.
Please @sgalles, @quintesse and @gavinking, could you confirm that it works now as you expect ?

**Comment by sgalles** [comment]
Yes @davidfestal it works for me.
