### ISSUE TITLE
imports of toplevel object members and toplevel class constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#1941]
See ceylon/ceylon-spec#928.

**Comment by tombentley** [comment]
@gavinking if my toplevel `object` itself has a member `object` then at the `import` site:

    import pkg{toplevel{inner}}

I get a typechecker error about an ambiguous member declaration 'inner' of 'toplevel'.

**Comment by gavinking** [comment]
Would you please open an issue; I at least need to improve the error message.

**Comment by tombentley** [comment]
@gavinking Suppose I can have

class Ctor {
    shared new Ctor {}
}

which I then import

    import pkg{Ctor{X=Ctor}};
    void f() {
        X();
    }

then I'm finding that the BTE's target (a `ProducedType` whose declaration is a `Constructor`) has a null `qualifyingType`. Previously the qualifying type of the type of a constructor has always been the type of the constructed class.

**Comment by tombentley** [comment]
I've implemented support for imports from top level objects. There may be some bugs remaining because in a number of places the code generator was making assumptions based on the `Base`-ness of the `Tree` which no longer apply.

Constructors still to do.

**Comment by tombentley** [comment]
@gavinking is it a typechecker bug that the target's qualifying type is null (last comment-but-one)?

**Comment by tombentley** [comment]
@gavinking is it a typechecker bug that the target's qualifying type is null (last comment-but-one)?

**Comment by gavinking** [comment]
Um. No, on the contrary, I think it's wrong if the constructor of a toplevel class has a _non-_null qualifying type!

**Comment by tombentley** [comment]
Well how then am I supposed to figure out the type of the instance that the constructor will instantiate?

**Comment by gavinking** [comment]
It's the immediate supertype of the constructor type.

**Comment by tombentley** [comment]
Doh! Of course. Thanks

**Comment by tombentley** [comment]
Should be fixed.
