### ISSUE TITLE
perplexing hash codes

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#1947]
It took me a while to figure out that this:

```ceylon
shared void run() {
    object o {
      shared actual Integer hash => -1;
    }
    print (o.hash); // prints "0"
}
```

isn't really a bug, since `$ceylontmp$hash$1 ^ $ceylontmp$hash$1 >>> 32` is used to avoid completely losing 32 bits worth of hash. As it turns out, it is discussed in #1334.

I don't know how often people actually test hash code implementations, but Whole.ceylon has tests for it (previously, just for positive hash values).

Perhaps it would be less confusing if 32-bit representable values were preserved. There may be also be an advantage to delaying any loss of hash until the 33rd bit, since as it stands, collisions in the 32 bit space are doubled; there are only 5 hash values for the numbers -5 to 4.

Or maybe it should just be documented. Or, maybe it's not a big deal, and I was just unlucky enough to see a "0" instead of a larger number where the sign change and off-by-one would have been obvious.

**Comment by tombentley** [comment]
`$ceylontmp$hash$1 ^ $ceylontmp$hash$1 >>> 32` is the same thing that `java.lang.Long.hashCode()` does and it has the advantage that it's simple and fast. If we tinker about to reduce the potential for surprise that's a cost which every hash has to carry. Hashes are already a source for confusion because (presumably) they can differ between platforms. So I'm inclined to think that some suitable documentation to the effect that a compiler is allowed to meddle might be the best solution to this one.

**Comment by FroMage** [comment]
I agree we should just document this.

**Comment by jvasileff** [comment]
One thing I just noticed is that sometimes you need control over the hash value. An example is Java's Map.Entry:

> int hashCode()
Returns the hash code value for this map entry. The hash code of a map entry e is defined to be:
    (e.getKey()==null   ? 0 : e.getKey().hashCode()) ^
    (e.getValue()==null ? 0 : e.getValue().hashCode())
This ensures that e1.equals(e2) implies that e1.hashCode()==e2.hashCode() for any two Entries e1 and e2, as required by the general contract of Object.hashCode.

which makes the correct Ceylon implementation:

```ceylon
    shared actual Integer hash
        => let (actual = key.hash.xor(\ivalue.hash))
           actual.xor(actual.rightLogicalShift(32));
```

(I think)

**Comment by quintesse** [comment]
Wouldn't this work as well?:

```ceylon
shared actual Integer hash
        => key.hash.xor(\ivalue.hash)).and(#ffffffff);
```

**Comment by jvasileff** [comment]
Hmm, yeah, that's easier to read :)
