### ISSUE TITLE
boxing issue with if/switch expressions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#1952]
```ceylon
void fun(Integer? arg) {
    value x = if (exists arg) then arg.string else 0.0;
}
```

Results in:

    Java primitive boxing/unboxing in Ceylon-generated code!

Same for this:

```ceylon
void fun(Integer? arg) {
    value y = switch (arg) case (null) 0.0 case (is Integer) arg.string;
}
```

**Comment by tombentley** [comment]
@gavinking the type of `if (true) then false else true` is `false|true`, apparently. Is that intentional, or should it be `Boolean`?

**Comment by gavinking** [comment]
@tombentley That's intentional, since we want the following to work:

```ceylon
\Itrue||\Ifalse = if (true) then false else true;
```

**Comment by tombentley** [comment]
Because of ceylon/ceylon-spec#865 you mean? But I thought that was on an as-yet unmerged branch?

**Comment by gavinking** [comment]
Thanks mate!
