### ISSUE TITLE
Incompatible types on functional parameter with tuple return type

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#1973]
```ceylon
void f([String,Character] g()) {
    value v = g();
}
```
> $ ceylon compile tmp
source/tmp/run.ceylon:2: warning: declaration is never used: 'v'
```ceylon
    value v = g();
         ^
```
source/tmp/run.ceylon:2: error: incompatible types
```ceylon
    value v = g();
               ^
```
  required: `Sequence`
  found:    `Object`
1 error
1 warning

As always, [generated code](https://gist.github.com/lucaswerkmeister/3dddd93a226552b9aaa1), `@noanno`’d. For some reason, the `Callable` parameter type is raw.

I found this [in `ceylon.ast`](https://github.com/ceylon/ceylon.ast/blob/c361370c363f5db5db6bcec1f488c724c372990e/source/ceylon/ast/samples/turingMachine/create.ceylon#L389), where it compiled fine for a while, so this is a relatively recent breakage (I’d guess no more than two weeks since I last ran `ant clean build` in `ceylon.ast`).

**Comment by lucaswerkmeister** [comment]
Guys, I’ve finally fixed all other errors in `ceylon.ast` (caused by RedHat AST changes), and after a month I’d really love to run my tests again… any progress or estimate on this?

**Comment by lucaswerkmeister** [comment]
Hm, that’s a better workaround… I widened the return type to `Anything` and then `assert`ed the return type I actually wanted.

**Comment by lucaswerkmeister** [comment]
It works, thanks a lot!

**Comment by lukedegruchy** [comment]
Works for me now.
