### ISSUE TITLE
ceylon-doc mangles signature of anonymous function, causing type check failure

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-compiler#1975]
Running ceylon-doc on this:

```ceylon
import ceylon.collection { PriorityQueue }

class A() {}

class B() {
    variable PriorityQueue<A>? queue = null;

    shared void method() {
        queue = PriorityQueue<A>((x,y) => smaller);
    }
}

void run() {
    B();
}
```

Yields this:
```
error [argument must be assignable to parameter 'compare' of 'PriorityQueue': 'Comparison(A, A)' is not assignable to 'Comparison(A, A)(A, A)'] at 9:33-9:48 of test/testme.ceylon
1 errors, 0 warnings
error [argument must be assignable to parameter 'compare' of 'PriorityQueue': 'Comparison(A, A)' is not assignable to 'Comparison(A, A)(A, A)'] at 9:33-9:48 of test/testme.ceylon
1 errors, 0 warnings
ceylon doc: Parsing failed with 1 error(s)

Usage:
ceylon doc [--cacherep=<url>] [--cwd=<dir>] [--define=<key>=<value>...] [--doc=
           <dirs>...] [--encoding=<encoding>] [--footer=<footer>] [--header=
           <header>] [--ignore-broken-link] [--ignore-missing-doc] [--ignore-
           missing-throws] [--link=<dir-or-url>...] [--maven-overrides=<url>] [
           --no-default-repositories] [--non-shared] [--offline] [--out=<url>]
           [--pass=<secret>] [--rep=<url>...] [--source=<dirs>...] [--source-
           code] [--src=<dir>...] [--sysrep=<url>] [--timeout=<seconds>] [--
           user=<name>] [--verbose[=<flags>]] [--] [<modules...>]

Run 'ceylon help doc' for more help
```

Do note that the code compiles normally when not using ceylon-doc

**Comment by FroMage** [comment]
This is due to the fact that the model loader for the compiler will not load private members but the loader for ceylondoc will (as will the metamodel one).

**Comment by FroMage** [comment]
Well, it also has to do with the fact that the type of the `compare` member is wrong in the reflection model loader.

**Comment by FroMage** [comment]
No, it's just wrong for every model loader if the functional parameter is shared apparently, because we generate the following method:

```java
@TypeInfo("ceylon.language::Callable<ceylon.language::Integer,ceylon.language::Tuple<ceylon.language::String,ceylon.language::String,ceylon.language::Empty>>")
    public final long g() {
        return ...;
    }
```

And this is the wrong `@TypeInfo` for that method.

**Comment by FroMage** [comment]
So I can fix this in new code, but the old code from < 1.1.1 will have invalid signatures, including the collection module. I _guess_ we could somehow fix this in the model loader if we bump the binary compat number (to be able to differentiate 1.1 and 1.1.1 (or whatever we end up calling this release), but that means we're starting to have code paths which accept older versions for BC.

**Comment by FroMage** [comment]
Right now we haven't bumped binary version for 1.1.1.

**Comment by gavinking** [comment]
Well we would have those code paths _temporarily_. We can drop them once we break BC.

**Comment by FroMage** [comment]
Fixed, but @chochos should note I've bumped the binary compat for the JS version too, so he will likely need to add code to make the 1.1.1 version also load the 1.1 version like I had to.
