### ISSUE TITLE
Compiler error calling set on ObjectArray using type alias

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#1977]
The following fails

```ceylon
class Foo() { }
alias FooArray => ObjectArray<Foo>;

void foo(FooArray array, Foo element) {
    array.set(0, element);
}
```

with

> compiler bug: Index: 0 at java.util.Collections$EmptyList.get(Collections.java:4465)

> compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:320)

The error does not occur when the alias is not used.

**Comment by tombentley** [comment]
Thanks for reporting @jvasileff
