### ISSUE TITLE
Add Ceylon @Name and  and @Method (and @LocalDeclaration ?) on anonymous methods

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#1978]
Is there a reason why such a construct :
```
return () => do(typedNode);
```
produces an anonymous class with no Ceylon `@Name` annotation ?

In the source Ceylon model produced by the type-checker, the name of the method declaration is `anonymous#8`

For anonymous objects, you add Ceylon annotations `Object`, `@Name` and `@LocalDeclaration` (with the qualifier id), but for such anonymous functions you don't it seems.

Would it be possible to add at least the `@Name` (and possibly the  `@Method` and `@LocalDeclaration`) annotations on such `AbstractCallable`-derived anonymous function classes ?

They are Ceylon declarations after all, so why not adding the Ceylon annotations that describe the Ceylon related information (and especially the declaration name) just as it is done for anonymous Object values ?

Sure, I know that, in this case, this is not necessary to reload things through the `ModelLoader`
and having things that work. But it makes it impossible to uniquely identify the source declaration from generated bytecode. This prevents us from building a reliable mapping between generated Java elements and the corresponding Ceylon source declarations, which is necessary for the debugging support.

For the moment I just have a special case when the name is an empty string and no annotation exist :
I assume there is only one such anonymous function in the same class or method scope but it seems a bit fragile to me.

**Comment by FroMage** [comment]
That looks fine to me, I guess, but we need to add tests. Especially in the language metamodel, where I don't want these callables to leak.

**Comment by FroMage** [comment]
Err, this gives me annotations on anonymous types:

```java
        final .java.lang.Object bug1845_2 = new .com.redhat.ceylon.compiler.java.language.AbstractCallable<.java.lang.Object>(.ceylon.language.Anything.$TypeDescriptor$, .ceylon.language.Empty.$TypeDescriptor$, "Anything()", (short)-1)
        @.com.redhat.ceylon.compiler.java.metadata.LocalDeclaration
        @.com.redhat.ceylon.compiler.java.metadata.Name("anonymous#5")
        @.com.redhat.ceylon.compiler.java.metadata.Method
        {
            
            @.java.lang.Override
            @.com.redhat.ceylon.compiler.java.metadata.Ignore
            public .java.lang.Object $call$() {
               
                return null;
            }
        };

```

That's not right, that's just wrong.

**Comment by FroMage** [comment]
Given that it's not possible to annotate anonymous classes, how do we propose to fix that? It may be possible if the JVM allows that, if we extend javac to support that, which is not clear that it's the case ATM (perhaps that actually works and the limitation is only encoded in the parser, which we bypass), but it's not clear that it would work.

**Comment by tombentley** [comment]
@FroMage I think it is possible to add annotations to anonymous classes in the tree (and they get emitted inthe bytecode), it's just that's it's not possible in Java source code. I pushed a patched version of compiler for David to try this out and he seemed to think it worked. I've not yet merged that patch into master (I need tests for it as you've pointed out).

**Comment by FroMage** [comment]
Right, that's the branch I was trying. I planned to fix the test `.src`, add tests and also check that the metamodel doesn't freak out. You think that's the right approach? Are we sure that the JVM doesn't care if anonymous classes have annotations?

**Comment by FroMage** [comment]
Thing is, if we have some anonymous classes in Java code that are supposed to be lambdas, we won't be able to use the same trick. Though the same limitation applies somewhat to multiple inheritance and to throws declarations.

**Comment by davidfestal** [comment]
It seems you does already add annotation to anonymous objects, don't you ?

**Comment by tombentley** [comment]
> Are we sure that the JVM doesn't care if anonymous classes have annotations?

I don't see why it should, it's a purely syntactic limitation as far as I'm aware. 

> if we have some anonymous classes in Java code that are supposed to be lambdas, we won't be able to use the same trick.

I don't understand.

**Comment by FroMage** [comment]
> I don't understand.

It means I can't write Java code manually that would return a Ceylon lambda as an anonymous class, since I can't annotate them. Though you can work around that by using a local class.

**Comment by FroMage** [comment]
Done and tested.
