### ISSUE TITLE
Optimize exponentiation for Integers

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#1979]
I noticed that for unknown or large exponents, `^` can cause a boxing chain:

```ceylon
void testExp() {
    value exp = 2;
    value result = 2 ^ exp - 1;
}
```

results in:

```java
final long result = .ceylon.language.Integer.instance(2L).power(.ceylon.language.Integer.instance(exp)).minus(.ceylon.language.Integer.instance(1L)).longValue();
```

Where I think it would be better to call `Integer.power(x, y)` directly. This doesn't affect anything I'm currently working on.

**Comment by FroMage** [comment]
Well, if this is 1.1.5 then #1560 should also be there, but every issue we add to 1.1.5 pushes back the release date for it.

**Comment by tombentley** [comment]
The problem seems to be that the operator transformations generally don't know about the value type methods that avoid boxing. The same issue affects `<=>` for example.

**Comment by sgalles** [comment]
@tombentley  @lucaswerkmeister This fix may have broken the compilation of `ceylon.formatter`
See : https://gist.github.com/sgalles/96b42fb3688cf97b2ec4
A simplified example of this problem :
This code when compiled :
```ceylon
assert([1].first>0);
```
with the CLI :
```
source\mymod\run.ceylon:3: error: no suitable method found for compare(Comparable<CAP#1>,long)
    assert([1].first>0);
                     ^
    method Integer.compare(long,long) is not applicable
      (actual argument Comparable<CAP#1> cannot be converted to long by method invocation conversion)
    method Integer.compare(Integer) is not applicable
      (actual and formal argument lists differ in length)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Comparable<? super CAP#1> super: Integer from capture of ? super Integer
```

**Comment by tombentley** [comment]
You're quite right @sgalles (and my apologies @lucaswerkmeister).

**Comment by tombentley** [comment]
@sgalles, @lucaswerkmeister this should now be fixed

**Comment by lucaswerkmeister** [comment]
Works here, thanks!
