### ISSUE TITLE
'let' not always evaluated

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#1982]
This code when executed
```ceylon
variable value var = 42;
value foo = let(bar = var = 1) 2;
print(var);
```
prints **42**
(it prints **1** with the JS backend)

FTR this code
```ceylon
variable value var = 42;
value foo = let(bar = var = 1) var;
print(var);
```
prints **1** with both backends

**Comment by FroMage** [comment]
OK this is scary because the code is good, but the bytecode is not good. The whole first `let` is missing in the bytecode.

**Comment by FroMage** [comment]
Fixed, for once it was not crazy hard ;)

**Comment by sgalles** [comment]
@FroMage Yeah, I'm trying to improve the `Criticity\PITA` ratio of my issues. 
Almost there. This one was *just* scary ;)
