### ISSUE TITLE
Java backend not parameterizing interface when type parameter is implicit

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#1983]
It appears to be legal to use an outer type parameter within an inner interface, but attempts to use such an interface fail.

```ceylon
void foo<Element>(
            MutableList<Element>|Array<Element> elements) {

    interface Setter {
        shared formal void set(Integer index, Element item);
    }

    Setter setter;

    switch(elements)
    case (is MutableList<Element>) {        
        object o satisfies Setter {
            // ERROR: o_ is not abstract and does not override abstract method set(long,java.lang.Object) in sandbox.ceylon.snap.base.foo$Setter_
            shared actual void set(Integer index, Element item) {
                elements.set(index, item);
            }
        }
        setter = o;
    }
    case (is Array<Element>) { /* ... */ }
}
```

The Java code for the interface includes a type parameter:

```java
interface foo$Setter_<Element> { ... }
```

But when used, it is not parameterized:
```java
final class o_ implements
  .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType,
  .sandbox.ceylon.snap.base.foo$Setter_ {
```

The code does compile if the interface is declared with `interface Setter<Element> { ... }`, of course with explicit parameterization everywhere Setter is used.

It also works to have `abstract class Setter() { ... }`. In this case, the abstract class is a Java inner class, so `Element` is already visible, and the class is not generic:

```Java
abstract class Setter implements .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType { ... }
````

p.s. Yes, there are cleaner ways to accomplish what the sample code is doing, but my war on Integer boxing led me here!

**Comment by tombentley** [comment]
This should now be fixed, but that bit of `makeJavaType()` could really do with being refactored.
