### ISSUE TITLE
Compiler and run tool reject some valid module and package names

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#1987]
AFAICT, the following are true:

1. The compiler *will not* compile `module`s with names that contain Java reserved words (seems to originate from `CeylonCompileTool.java`)
2. The compiler, or at least the build tool, does not seem to understand `\i` identifier escaping for `module` names
3. The compiler *will* compile `package`s that contain Java reserved words by means of name mangling (as expected)
4. The run tool *will not* run functions in `package`s with names that contain Java reserved words, i.e. `ceylon run: Could not find toplevel method 'ceylon.math.long.longTesting’.` (Perhaps `CeylonRunTool.java` in `ceylon-runtime`?
5. At least WRT 1 and 2, different error messages may occur based on the characters used for the module name, or the inclusion of Java and/or Ceylon reserved words.

I'm basing this off my understanding of valid identifiers based on the following from the spec:

>4.1.2:
FullPackageName: PackageName ("." PackageName)*
3.1:
PackageName: LIdentifier
2.3:
LIdentifier: LowercaseCharacter IdentifierCharacter* | "\i" IdentifierCharacter+
...
The following reserved words are not legal identifier names unless they appear escaped using \i or \I:
￼￼assembly module package import alias class interface object given value assign void function new of extends satisfies abstracts in out return break continue throw assert dynamic if else switch case for while try catch finally then let this outer super is exists nonempty

The following can be used to try out various module names:

```bash
MODULE_NAME='hello.float'

ceylon new hello-world \
    --ant=false \
    --eclipse=false \
    --module-version=1.0.0 \
    --module-name=$MODULE_NAME \
    -- hello

pushd hello

ceylon compile-js $MODULE_NAME &&
ceylon run-js $MODULE_NAME &&
ceylon compile $MODULE_NAME &&
ceylon run $MODULE_NAME 
```

I used Eclipse to try to run functions in packages with unsupported names.

**Comment by FroMage** [comment]
So should `ceylon new` reject ceylon keywords in the module name or quote them with `\i`?

**Comment by jvasileff** [comment]
My two cents - accept arguments iff they are valid `LIdentifier` or `UIdentifier`s. So the user would have to provide the `\i` or `\I`. This would also help for cases like `ceylon run` for `shared void \iUpperRun() { ... }`.

**Comment by FroMage** [comment]
OK, so I've fixed everything in theory, but please check. I've come to the conclusion that tools should not expect module names to be quoted for either Java nor Ceylon keywords. Java keyword quoting is supposed to be invisible to users, and Ceylon keyword quoting only occurs as artifact of the Ceylon parser and is not reflected in module names, so you should be able to use `long.module` and the tools will quote to `$long.module` or `long.\imodule` depending on where it needs to go.

**Comment by jvasileff** [comment]
That's great, thanks! I saw something about now being a bad time to update, so I'll wait a few days before testing.
