### ISSUE TITLE
Ceylondoc: line anchors broken in source files

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#1988]
http://modules.ceylon-lang.org/test/ceylon/language/1.1.0/module-doc/api/Iterable.ceylon.html#1022,1069

This used to work before we switched syntax hilighter I think.

**Comment by FroMage** [comment]
@thradec do you have time to look at this?

**Comment by thradec** [comment]
sure

**Comment by FroMage** [comment]
Great :)

**Comment by thradec** [comment]
Done.

**Comment by FroMage** [comment]
Great, thanks!

**Comment by FroMage** [comment]
You want other bugs to fix? :)

**Comment by thradec** [comment]
what?! there can't be any other bugs :-)

**Comment by thradec** [comment]
give it to me

**Comment by FroMage** [comment]
Well, not necessarily limited to ceylondoc…
