### ISSUE TITLE
Strange error message for constructor in anonymous class

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#1994]
This code :
```ceylon
object bar{
    shared new Foo(){}  
}
```
compiled with CLI
```
source\mymod\run.ceylon:5: error: anonymous class may not have constructor
    shared new Foo(){}
              ^
source\mymod\run.ceylon:5: error: constructor bar_ in class bar_ cannot be applied to given types;
    shared new Foo(){}
                    ^
  required: Foo
  found: no arguments
  reason: actual and formal argument lists differ in length
```
The second error message is strange.
And it also causes a backend error in the IDE
FTR : I don't expect this to compile eventually.

**Comment by tombentley** [comment]
@gavinking shouldn't this be prohibited by the typechecker? `object` declarations don't have constructors or initializers because they're instantiated implicitly, because they're values.

**Comment by gavinking** [comment]
It is rejected by the typechecker. The first msg is from the typechecker.

**Comment by tombentley** [comment]
@gavinking my apologies I assumed it was a javc error.

**Comment by tombentley** [comment]
Thanks @sgalles for reporting.
