### ISSUE TITLE
Boxing of arithmetic expressions

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#1996]
The `BoxingVisitor` only marks arithmetic expressions as unboxed when both operands are unboxed. In this respect arithmetic operators are treated differently to other binary operators (such as `&&`) which are marked as unboxed irrespective of the boxing of their operands.

The effects of this is for arithmetic with one boxed and one unboxed operand to favour boxing, like this:

    n1 = n2.plus(.ceylon.language.Integer.instance(n3)).longValue();

It seems to me that this is suboptimal because we have to instantiate a box to invoke the method and the method has to box its result, resulting in the creation of two boxes.

It seems to me that it would be better to treat arithmetic identically with the other binary operators and always unbox the operands, which will only result in a box instantiation in the event that the result needs to be boxed (and even then it's only 1 box not two):

        n1 = n2.longValue() + n3;

**Comment by FroMage** [comment]
Well, for booleans we _have_ to unbox because there are no methods to call for `&&` (no overloading). For math, the logic was that if one of the two is boxed and we don't really know if we caller wants them boxed we may as well keep it all boxed and avoid unboxing to rebox later.

Now, without statistical/perf evidence I honestly don't know if we should always unbox, or unbox if at least one term is unboxed, or if both are. It's not clear at all to guess without evidence.

**Comment by tombentley** [comment]
> we may as well keep it all boxed and avoid unboxing to rebox later.

But the method on the box that we end up calling has to "unbox" to get the primitives, add them and then rebox them into the return value anyway, so I don't see that there's any advantage to doing boxed arithmetic at all.

**Comment by quintesse** [comment]
>  so I don't see that there's any advantage

Indeed, the boxed versions are always more costly in arithmetic.

The only time we could worry about statistics is when choosing the type of a local.
A simple example:

```ceylon
Integer n = 1;
for (i in 1..10) {
    print(n);
}
```

The local `n` here will be boxed 10 times even though for us in this case it would be obvious that it would be best to keep the boxed version around. But I guess that figuring *that* out is hard.

**Comment by tombentley** [comment]
@quintesse that's #1464.

**Comment by quintesse** [comment]
@tombentley Ok, cool, didn't know there was already an issue for that.

**Comment by tombentley** [comment]
I've made this change.

**Comment by tombentley** [comment]
This has been in master for a few days and no one has complained that I broke anything, so I'm going to close this.
