### ISSUE TITLE
Change metamodel literals for spec change

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#1998]
See ceylon/ceylon-spec#1162

**Comment by tombentley** [comment]
Someone needs to start work on this, unlike some of the remaining issues it's not really something we can put off to 1.3.

**Comment by tombentley** [comment]
While looking at this I found that

    object toplevel {
        shared class Member() {}
    }
    void run() {
        value z=  `toplevel.Member`;//syntex error expecting initialial lower-case identifier
    }

Of course metamodel refs to attributes and method of the anonymous class are allowed, so it's weird that classes are not. Can you explain @gavinking?

**Comment by gavinking** [comment]
I guess it's because they used to be non-denotable types. Open an issue against spec.

**Comment by tombentley** [comment]
This is basically done, but I need to add tests for `obj.Class.Ctor`

**Comment by tombentley** [comment]
@gavinking considering the following:

```ceylon
class ClassContainer(){
    shared object memberObject {
        shared class Ctor {
            shared new Ctor() {}
            shared new Other() {}
        }
    }
    shared void test(ClassContainer other){
        MemberClassConstructor<\ImemberObject,\ImemberObject.Ctor.Ctor,[]> ctorCtor = `\ImemberObject.Ctor.Ctor`;
        print(ctorCtor(other.memberObject)());
        MemberClassConstructor<\ImemberObject,\ImemberObject.Ctor,[]> ctorOther= 
                `\ImemberObject.Ctor.Other`;
    }
}
```

When I reference the constructor `Ctor` the `Type` of the `MemberClassConstructor` (i.e. it's second type argument) is allowed to be `\ImemberObject.Ctor.Ctor`, but it should simply be `\ImemberObject.Ctor` I think. Certainly in the case of a non-default constructor the type argument must be `\ImemberObject.Ctor` and `\ImemberObject.Ctor.Other` is rejected because "constructor is not a type: Other".

**Comment by tombentley** [comment]
This should all now work, though my question to @gavinking above still stands.

**Comment by gavinking** [comment]
@tombentley yeah OK, would you do me a favor and open a separate issue for that, please, it's nothing at all to do with metamodels.
