### ISSUE TITLE
Compiler exceptions on invalid code

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2008]
See https://gist.github.com/lahwran/be6d731c4e8701ca0de9#file-gistfile1-txt-L95

**Comment by tombentley** [comment]
Should be fixed.

**Comment by FroMage** [comment]
Thanks a lot! Did you add a test?

**Comment by tombentley** [comment]
No I didn't. I had to hand-apply the diff from the patch in order to reproduce, and the project involved has java dependencies etc etc etc, so constructing a test case would be ~~quite~~ a lot of work.
