### ISSUE TITLE
Annotation interop for package annotations

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2009]
Currently the annotations applied to a ceylon package descriptor get applied to the `package_` class. This means that it's not possible to use Java annotation types which are constrained to (or intended for) the `package-info.class`. 

This is further to #1471

**Comment by tombentley** [comment]
Actually, this isn't really necessary, because in this situation the user can just write a `package-info.java` (along side their package.ceylon) and javac will do its usual thing.

**Comment by FroMage** [comment]
So IIRC the reason why we ended up with `package.class` was that we wanted to be able to put code in there at some point (like we did for modules at some point). I wonder if we shouldn't reevaluate it entirely and produce `package-info.class`…
