### ISSUE TITLE
Java interop annotations on generated setters

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2010]
#1471 added a mechanism to disambiguate the Java element in which to apply annotations. However, there remains no way to specify an annotation on generated setters of attributes. The following:

```ceylon
late inject__METHOD Sql sql;
```

applies the annotation to the generated *getter*, while:

```ceylon
late inject__FIELD Sql sql;
```

of course applies the annotation to the *field*. Unfortunately, using a field annotation here circumvents the attribute initialization check (the setter must be called in order to set `this.$init$sql = true;`).

So, the suggestion is to support `annotationType__SETTER` when annotating uninitialized or variable attributes, and perhaps `annotationType__GETTER` for symmetry.

**Comment by tombentley** [comment]
@jvasileff that should work for you know, though because Java's `ElementType` enumeration doesn't distinguish `GETTER`/`SETTER` from `METHOD` I think sometimes the warning messages produced by the compiler might be a little confusing.

**Comment by jvasileff** [comment]
Awesome, thanks @tombentley!
