### ISSUE TITLE
default arguments and inheritance

### ISSUE THREAD

**Issue by LisiLisenok16** [ceylon/ceylon-compiler#2013]
return type of subclass actual method can be class or interface which extends / satisfies corresponding return type of superclass method. But if there default arguments specified all is not so obvious... Look below code for example

	interface Car {}
	interface BigCar satisfies Car {}
	class Truck() satisfies BigCar {}
	
	interface Driver {
		shared formal Car driveCar( Float speed = 0.0 );
	}
	interface ExperiencedDriver satisfies Driver {
		shared formal actual BigCar driveCar( Float speed );
	}
	class Trucker() satisfies ExperiencedDriver {
		shared actual BigCar driveCar( Float speed ) {
			return Truck();
		}
	}
	
	ExperiencedDriver d = Trucker();
	
	Car carA = d.driveCar(); // ok
	Car carB = d.driveCar( 1.0 ); // ok
	BigCar carBigA = d.driveCar( 1.0 ); // ok
	BigCar carBigB = d.driveCar(); // Incompatible types required: $BigCar_ found: $Car_

**Comment by tombentley** [comment]
Thanks for reporting @LisiLisenok16
