### ISSUE TITLE
NPE for innocent code (multiple symbols not found)

### ISSUE THREAD

**Issue by AnhNhan** [ceylon/ceylon-compiler#2016]
Only tried it with Ceylon 1.1 vanilla Windows, CLI, not with master yet. Looking at the issues, nothing makes me believe it has been fixed though.

Stack trace & some environment info. NPE seems to be coming from tree-walking while de-sugaring within Sun's compiler tools. I'm not too familiar with the compiler tools, though, so I leave the detailed analysis to you guys.

https://gist.github.com/AnhNhan/22643232fd76b4aa693a

Code I was trying to compile (no dependencies except for the given imports). I don't think it's too fancy.

https://gist.github.com/AnhNhan/220a7f70118ba05410b7

**Comment by gavinking** [comment]
Hi, thanks, could you please open an issue against the ceylon-compiler project?

**Comment by quintesse** [comment]
Seems to compile just fine here.

**Comment by quintesse** [comment]
In fact, I can. Just not in the IDE somehow.

**Comment by FroMage** [comment]
> Hi, thanks, could you please open an issue against the ceylon-compiler project?

Uh, this _is_ an issue on `ceylon-compiler` ;)

**Comment by gavinking** [comment]
Ah, haha, I thought it was the email list :)

**Comment by quintesse** [comment]
Smallest example that will show this bug:

```ceylon
void bug() {
    Integer? wordBoundary = null;
    switch (wordBoundary)
    case (is Null)
    { }
    case (0)
    { }
    else
    { }
}
```

**Comment by quintesse** [comment]
Generated code is:

```java
public static void bug() {
   final .ceylon.language.Integer wordBoundary = null;
    {
        .java.lang.Object sel$0 = wordBoundary;
        if (sel$0 == null) {
            final .java.lang.Object wordBoundary$2 = (.java.lang.Object)sel$0;
        } else if (sel$0 != null && sel$0.longValue() == 0L) {
        } else {
            final long wordBoundary$1 = ((.ceylon.language.Integer)sel$0).longValue();
        }
    }
}
```

**Comment by quintesse** [comment]
Fixed.

**Comment by AnhNhan** [comment]
Thanks, guys.
