### ISSUE TITLE
Java interop: setter not visible when getter is protected

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2019]
For this Java class with asymmetric visibility on the getter/setter pair for `prop`:

```java
public class JavaBean {

    private String prop;

    protected String getProp() { // or package private
        return prop;
    }

    public void setProp(String prop) {
        this.prop = prop;
    }

}
```

It is not possible to call `setProp` from Ceylon code in a different package:

```Ceylon
shared void testing() {
    value jb = JavaBean();
    jb.prop = "value"; // error
    // Protected method or attribute is not visible: prop of type JavaBean
}
```

The opposite works - reading from a `public` getter when the setter is `protected`.

If the getter is made `private`, the setter is instead exposed as a method and can be used.

And yes - this actually **is** something that exists in the wild.

**Comment by tombentley** [comment]
So I guess in a case like this we should expose the setter as a method.

But @gavinking always wanted to always expose the getter and setter as methods as well as a single attribute, and I wonder whether we've just not done that yet or whether there as some good reason we've not done it yet.

**Comment by quintesse** [comment]
Well, wouldn't that just give us more possibilities for name clashes in other circumstances? (Not that I can think of any of the top of my head without resorting to farfetched things)

**Comment by FroMage** [comment]
That requires a lot more logic because people would then have the ability to override all of the attribute, getter and setter methods, which we should disallow. Or override a single one of them where it does not necessarily make sense.

**Comment by gavinking** [comment]
@FroMage I don't think that's right. You could make the getter and setter methods final.

**Comment by FroMage** [comment]
`abstract final`?
