### ISSUE TITLE
error: imported package is not shared

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2024]
Importing a class in a Java source file within a Ceylon module causes the class's package to not be available for import in Ceylon source files.

For a `ceylon new simple` project, with:

JavaClass.java
```java
package com.example.simple;

import ceylon.time.Instant;

public class JavaClass {}
```

run.ceylon
```ceylon
import ceylon.time { Instant }

shared void run() { 
    Instant(0);
}
```

module.ceylon
```ceylon
module com.example.simple "1.0.0" {
    import ceylon.time "1.1.1";
}
```

package.ceylon
```ceylon
package com.example.simple;
```

you get:

```bash
$ ceylon compile 
warning: Package class ceylon.time contains no name, ignoring it
source/com/example/simple/run.ceylon:1: error: imported package is not shared: 'ceylon.time'
import ceylon.time { Instant }
      ^
1 error
1 warning
Note: Created module com.example.simple/1.0.0
ceylon compile: There was 1 error
```

Note: this error does not occur in the IDE.

**Comment by FroMage** [comment]
So, this is due to unfortunate things:

- we can't load the annotations of `ceylon.time.package_` at the same time as we complete it _if_ there is already a Javac `enter` phase going on.
- we process java sources in Javac `enter` phase, which then has added code to validate that imports come from imported modules, but since we do this during an `enter` phase, we get the package symbol, but we can't get its annotations
- it works for ceylon code because we do this loading of imported packages outside an `enter` phase.

Now let's figure out how to solve this…

**Comment by FroMage** [comment]
I _guess_ that a workaround is to not import the type and use it fully-qualified. @jvasileff can you try that to see if you can work around it until I figure how to fix it?

**Comment by FroMage** [comment]
Perhaps one way to fix this is to do a pre-visit of the java trees for imports, since that's all that is done during the problematic `enter` phase.

**Comment by FroMage** [comment]
Well, not so trivial, we need to make sure in `import foo.Bar` that `foo` is a package and not a type, which is done in `enter`. We also can't delay the check until a later phase because we would not be attributing the error symbol on the right import node.

**Comment by jvasileff** [comment]
> can you try that to see if you can work around it until I figure how to fix it?

Yes, of course. In fact, my sdk pull request basically is my workaround.

If this isn't for 1.2, I think it would be nice to have a "not supported" error if possible. Narrowing this down took quite a while!

**Comment by FroMage** [comment]
OK fixed.

**Comment by bjansen** [comment]
I have the opposite problem now: if the Java file uses fully qualified class names instead of imports, I get the same error as @jvasileff had...
In my case, those Java files are generated by jooq, so it seems I can't modify them to use imports instead of fqcn.

**Comment by FroMage** [comment]
Please open a new issue.
