### ISSUE TITLE
Incompatible types error when extending MutableList

### ISSUE THREAD

**Issue by kingjon3377** [ceylon/ceylon-compiler#2033]
The following code fails to compile with the error "types List<Object> and Iterable<T,Object> are incompatible; both define repeat(long), but with unrelated return types":

```ceylon
interface MweList<T> satisfies MutableList<T> { }
```

**Comment by gavinking** [comment]
Confirmed. Nasty! Thanks.

**Comment by FroMage** [comment]
OK, so this is javac looking at class files and complaining, because `ListMutator<T>` is a `List<Object>` while `MutableList<T>` is a `ListMutator<T> & List<T>`.

**Comment by gavinking** [comment]
So it works for LinkedList and ArrayList. Why is an interface different?

**Comment by FroMage** [comment]
Well, it's even worse because for some reason if I change the order of satisfied interfaces in `MutableList` the SDK stops compiling at _other_ places which I can't seem to reproduce in tests ATM.

**Comment by FroMage** [comment]
OK, split the other issue to #2048.

**Comment by FroMage** [comment]
Given that this error only happens on interfaces, and not on abstract or regular classes (why?) I'm inclined to say we can skip this error.

**Comment by gavinking** [comment]
"skip"? what?

**Comment by FroMage** [comment]
I mean, disable this error when looking at Ceylon source code… I don't like it because I can't really discriminate easily between legitimate errors and this special case so I'll have to disable it even for invalid code, but there's not much I can do…

**Comment by gavinking** [comment]
You mean in javac? Yes, I think that's fine.

**Comment by FroMage** [comment]
Actually this error also happens on abstract classes, as long as there's no default implementation of the method (otherwise we sneak the method in) so we only get the error when the method is not overridden explicitly. So perhaps another way to tackle this would be to always redefine the method as an abstract method. But again we're back at detecting which methods we need to redefine magically, which is not trivial.

**Comment by FroMage** [comment]
Done, but not by tweaking javac. I now emit an extra abstract method on interfaces that implement two interfaces with different type args. That makes javac shut up. I found lots of other issues during that bug fix though.
