### ISSUE TITLE
@Annotations(@Annotation("shared")) is amazingly wasteful

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2035]
Check this out:

```java
@.com.redhat.ceylon.compiler.java.metadata.Ceylon(major = 8)
@.ceylon.language.DocAnnotation$annotation$(description = "Hello world")
@.ceylon.language.AuthorsAnnotation$annotation$(authors = "Gavin")
@.com.redhat.ceylon.compiler.java.metadata.Annotations({
        @.com.redhat.ceylon.compiler.java.metadata.Annotation(
                value = "doc",
                arguments = {"Hello world"}),
        @.com.redhat.ceylon.compiler.java.metadata.Annotation(
                value = "by",
                arguments = {"Gavin"})})
interface Stuff {}
```

Duplicate information is stored in a very wasteful format for no apparent reason. I propose that:

1. we stop storing doc annotation and user-defined annotations in `@Annotations`, and
2. we encode language annotations into @Annotations using a `modifiers` integer.

This could be done without breaking backwards compatibility.

**Comment by tombentley** [comment]
Early indications are this will make the dist `.zip` about 6% smaller if we're using a `long` to encode the modifiers.

**Comment by gavinking** [comment]
Seems worthwhile to me.

**Comment by tombentley** [comment]
Sorry, I was completely wrong because I was looking at size of the wrong files. Whether we use an `int` or a `long` we're looking at the language module `.car` being less than 1% smaller.

**Comment by quintesse** [comment]
Doesn't surprise me, strings are only stored once if they're exactly the same. It just *looks* wasteful in the (fake) generated Java source.

**Comment by FroMage** [comment]
Well, why again didn't we remove the `@Annotations` one? I think it predates support for annotations, no?

**Comment by tombentley** [comment]
IIRC because the model loader can't use the `@Shared$annotation` and friends because we can't put those on `native` things in the language module. In turn because of the bootstrap problem.

**Comment by FroMage** [comment]
Mmm, why not? We are able to use the metamodel defined in Ceylon in its Java implementation, though.

**Comment by tombentley** [comment]
Because in order to do annotation processing javac completes annotations very early on, before the model loader is involved in anything.

**Comment by FroMage** [comment]
Oh, so it's different for annotations? Well, we could _still_ stop generating `@Annotations` if we're not bootstrapping ;)

**Comment by tombentley** [comment]
> Oh, so it's different for annotations?

yes

> Well, we could still stop generating `@Annotations` if we're not bootstrapping ;)

No the problem is using stuff like `@Shared$annotation` doesn't exist for javac when we're compiling natives, so we get a no such symbol. javac has no way to know that the symbol will be defined, because we only enter it into the symbol table during a later phase. I think I described the pb wrongly before, but it's been a while since I looked at it. But I do remember it's a pretty hard one to solve.

**Comment by FroMage** [comment]
I don't get it. If we're not compiling the language module, then `@Shared$annotation` must be resolvable.

**Comment by tombentley** [comment]
Well it was probably about 12 months ago that I was looking at this, so I could be confused, but the problem is what https://github.com/ceylon/ceylon.language/issues/408 is about. When we're compiling the natives in the language module javac tries to complete annotation types like `@Shared$annotation` before our compiler get's a look-in.

**Comment by FroMage** [comment]
Again, I can believe you _when bootstrapping_, but that should not be true for any other module.

**Comment by tombentley** [comment]
Yes, it's during bootstrapping.

**Comment by FroMage** [comment]
So we _should_ be able to not generate these annotations when not bootstrapping then :)

**Comment by tombentley** [comment]
Well obviously I don't understand how the hell the bootstrapping stuff works, but if that's all it needs... let's have a try.

**Comment by quintesse** [comment]
Meaning we keep the code that knows how to *read* both types of annotations but we *use* the older type only when compiling the language module, right?

**Comment by FroMage** [comment]
Yes, that would be a good start.

**Comment by tombentley** [comment]
Well, sure we could annotate all the native stuff with `@Annotations(modifiers=243)` (by hand) if you like. But that would be a *lot* of effort and it still wouldn't fix ceylon/ceylon.language#408 because the annotations are read at runtime using the "real" `@Shared$annotation` annotation. Of course we could *also* change the way we read language module annotations at runtime, so everything was consistent.

Or we could try to fix the real problem.

**Comment by gavinking** [comment]
Because it is ugly when I turn on logging to see the generated Java schema and have my eyes hurt like someone shoved a stick in them.

That's reason enough.

**Comment by quintesse** [comment]
Go see an optician :)

**Comment by tombentley** [comment]
More fiddly than I would have liked, but hopefully Gavin's eyesight is safe for the time-being.

**Comment by gavinking** [comment]
Thanks! :)

**Comment by FroMage** [comment]
So we didn't remove the `$Shared$annotation` when we have the info in `@Annotation(modifiers = x)`? Why not?

**Comment by gavinking** [comment]
We need the `$Shared$annotation` for the metamodel, don't we?

**Comment by FroMage** [comment]
Also, I think we're better off with the modifier masks somewhere in the language module's `metadata` package so that they can be defined manually in Java code without pulling the compiler module.

**Comment by FroMage** [comment]
> We need the `$Shared$annotation` for the metamodel, don't we?

Well, only if the metamodel can't produce it out of thin-air when required.

**Comment by tombentley** [comment]
> So we didn't remove the `$Shared$annotation` when we have the info in `@Annotation(modifiers = x)`? Why not?

That's what ceylon/ceylon.language#408 is about, and it would involve a similar duplication of code paths in the metamodel. Plus duplicated testing. That's quite a lot more work than this was.

> Also, I think we're better off with the modifier masks somewhere in the language module's metadata package so that they can be defined manually in Java code without pulling the compiler module.

I can't really parse that sentence, but I don't have an opposition to putting the masks somewhere else if they need to be shared. Which they would if the metamodel was to read them at runtime.

**Comment by FroMage** [comment]
I meant that if we have to write native code:

```java
@Annotations(modifiers = CeylonModifier.SHARED | CeylonModifier.ABSTRACT)
```
then it's better if the constants live in the language module's `metadata` package rather than in the compiler package.

**Comment by FroMage** [comment]
> rather than

Or in addition to if we can't make it work.

**Comment by tombentley** [comment]
Yes, in addition to because the flags being defined in ceylon.language doesn't help because that's not on the classpath of the compiler.
