### ISSUE TITLE
class with empty initializer missing line number info

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2043]
I have:

```ceylon
shared void run() {
    print(Bar());
}
class Bar() {}
```

When I try to step into the instantiation of `Bar`, the IDE complains about missing line number info.

**Comment by gavinking** [comment]
I lie. It's choking on `Bar.<clinit>`, not `Bar.<init>`.

So I think it's actually the line of code that initializes `$TypeDescriptor$` that has no line number info.

**Comment by tombentley** [comment]
@gavinking I can't reproduce this: When I step into the instantiation of `Bar` is works fine.

**Comment by tombentley** [comment]
Actually, the initialization of the `$TypeDescriptor$` gets line number information when it doesn't correspond to anything in the original source code. That seems incorrect to me, I think we should generate that code with no line info. For me that still wouldn't elicit the IDE warning that @gavinking complained about.

**Comment by tombentley** [comment]
With a breakpoint on the line with `print` I can step in and first time I do so I get a stackframe for `<cinit>` that has no line number info (but that's just shown on the stackframe in the Debug view, I don't get a dialog or anything you'd call a complaint). If I step out of the `<cinit>` and then step in again I get to the constructor on line 4 as I would expect.

So I think this is working.
