### ISSUE TITLE
wrong line numbers for statement with annotations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2047]
Given:

```ceylon
shared void runme() {
    value f = (String name) => name.uppercased;
    suppressWarnings("unusedDeclaration")
    String string = f("hello");
}
```

The line number in the class file of the invocation of `f` is actually the line number of the `suppressWarnings` annotation.

**Comment by gavinking** [comment]
Oh wait, this is much worse. If I change the code to:

```ceylon
shared void runme() {
    value f = (String name) 
            => name.uppercased;
    suppressWarnings("unusedDeclaration")
    String string = 
            f("hello");
}
```

Then stepping _completely skips over_  the call to `f`. Nasty!

**Comment by gavinking** [comment]
So the problem is, I guess, not actually so closely related to the annotation.

**Comment by tombentley** [comment]
We need to use the identifier of the attribute definition to ascribe the line number, rather that the definition itself (which, because it includes the annotations, can start on an earlier line). 

But for the `f("hello")` call I cannot get the compiler to ascribe the correct line number for that.

**Comment by tombentley** [comment]
This should be fixed.
