### ISSUE TITLE
Interop: Generic array creation w/spread operator

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2053]
When calling the java method `accept`:

```java
package com.vasileff.ceylon.guava.collect;

public class Varargs {
	@SafeVarargs
	public static <T> T accept(T... ts) {}
}
```

```ceylon
shared void callVarargs<Element>({Element*} items)
        given Element satisfies Object {
    Varargs.accept(*items);
    // Beackend Error: Generic array creation
}
```

the compiler attempts to create a Java `Element[]` instead of creating an `Object[]`, and then casting to `Element[]`.

**Comment by tombentley** [comment]
There's a related bug when the type parameter has an upper bound, which unfortunately looks like it's harder to fix.

**Comment by tombentley** [comment]
That was difficult, but should now be fixed.
