### ISSUE TITLE
compiler bug on lazy specification of callable attribute qualified with `this`

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2056]
```ceylon
class C() {
    String() s;
    this.s() => "";
}
```
> error: compiler bug: com.redhat.ceylon.compiler.typechecker.model.Value cannot be cast to com.redhat.ceylon.compiler.typechecker.model.Method at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformAssignment([ExpressionTransformer.java:4747](https://github.com/ceylon/ceylon-compiler/blob/68da287c4c7f3972724b2b3ed6eab7fd4ea18ea1/src/com/redhat/ceylon/compiler/java/codegen/ExpressionTransformer.java#L4747))
1 error
<sup>Generated by [linkStackTrace](http://lucaswerkmeister.github.io/linkStackTrace/)</sup>

Found while working on ceylon/ceylon.ast#78; see also #1913 (@tombentley).

**Comment by lucaswerkmeister** [comment]
(Doesn’t occur when `s` is declared as `String s();`.)

**Comment by tombentley** [comment]
Should be fixed.

**Comment by lucaswerkmeister** [comment]
Thanks!
