### ISSUE TITLE
Interop: null assertion error on "is" test

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2058]
It would be nice if the null check could be skipped for assignability conditions.

```ceylon
import java.util {
    JHashMap=HashMap
}

shared void nullTest() {
    value hm = JHashMap<String, Object>();
    if (is String item = hm.get("")) {}
    // ceylon.language.AssertionError "null value returned from native call not assignable to Object"
}
```

The spec also has:

>Every existence or nonemptiness condition is equivalent to—and may be considered an abbreviation of—an assignability condition:
>
> * exists x is equivalent to is Object x, and

**Comment by tombentley** [comment]
@jvasileff I think that should work for you now.
