### ISSUE TITLE
Calling nothing => compiler bug in AbstractTransformer.isUnknownTuple

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2066]
```ceylon
Anything a1 = nothing();
```
> compiler bug: null at com.redhat.ceylon.compiler.java.codegen.AbstractTransformer.isUnknownTuple([AbstractTransformer.java:2377](https://github.com/ceylon/ceylon-compiler/blob/a8a6d06c784eb9ddc9d648fe36b19aa83e459e63/src/com/redhat/ceylon/compiler/java/codegen/AbstractTransformer.java#L2377))
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression([ExpressionTransformer.java:323](https://github.com/ceylon/ceylon-compiler/blob/224affa55c11d6bb2a521d995576bd8afbebac7b/src/com/redhat/ceylon/compiler/java/codegen/ExpressionTransformer.java#L323))
compiler bug: visitor didn't yield any result at unknown

Happens for any expression of type `Nothing`, not just `nothing`:
```ceylon
Nothing n = nothing;
Anything a2 = n();
```

<sup>PS: As a “bug golf” entry, this can be reproduced in just 14 characters: `[]n=nothing();`</sup>

**Comment by tombentley** [comment]
@gavinking in the expression of the specifier of 

    String c = nothing(4, "");

the expression's type is `unknown`, rather than `Nothing` as I would have expected. Is that a bug in the typechecker?

**Comment by gavinking** [comment]
Hrm, interesting. No it's not a big precisely, but sure, I can see how it could be better...

**Comment by tombentley** [comment]
@gavinking do those ellipses mean that a change to the typechecker will be forthcoming?

**Comment by gavinking** [comment]
If you open an issue, sure.

On Mon, Feb 23, 2015 at 3:00 PM, Tom Bentley <notifications@github.com>
wrote:

> @gavinking <https://github.com/gavinking> do those ellipses mean that a
> change to the typechecker will be forthcoming?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2066#issuecomment-75544846>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
