### ISSUE TITLE
Backend error working with denotable types for objects

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2082]
The type checker allows a value to be of a denotable object type, but the backend doesn't support this:

```ceylon
interface Escapable of eName, eText {}

object eName satisfies Escapable {
    shared Boolean isValid(String val) => false;
}

object eText satisfies Escapable {}

Boolean isValid(String val, Escapable type) {
    if (is \IeName type) {
        return type.isValid(val);
        // cannot find symbol
        //      symbol:   method isValid(java.lang.String)
        //      location: variable type$256 of type java.lang.Object
    }
    return true;
}
```

Although I've run into other issues that make me wonder what the correct behavior is, since values holding objects seem to want to be of type `Basic & <list of non-object types>`:

```ceylon
object someObject {}
void testing() {
    value x = someObject; // x is "Basic", not "\IsomeObject"
    value y = eName; // y is "Basic&Escapable"
}
```

**Comment by gavinking** [comment]
> Although I've run into other issues that make me wonder what the correct behavior is,

As defined in §3.2.9, the typechecker goes out of its way to not _infer_ anonymous class types. You have to be explicit if you want one.

**Comment by jvasileff** [comment]
Thanks for the pointer. I really do need to spend some time studying the spec to better understand things like this and also coverage.

A naive request would be for these newly-denotable types to be inferred, in order to make it easier to avoid defining companion types like `Finished`. But I understand there may be a lot more to this.

**Comment by tombentley** [comment]
The `&Basic` gets added by the call to `denotableType()` was added as the solution to #2012. I didn't realise that `denotableType()` might do that.

**Comment by gavinking** [comment]
> I didn't realise that `denotableType()` might do that.

Of course! `Basic` is a common superclass. As defined by §3.2.9, anonymous classes are replaced by the intersection of their supertypes in any inferred type.

**Comment by tombentley** [comment]
The best I can really think of for this then is to remove any `&Basic` or `&Object` which might appear in the result of `denotableType()` when we're using it for type narrowing like this. Maybe @FroMage can think of something better?

**Comment by FroMage** [comment]
Well, no that seems right. I guess `simplifyType` should be amended to handle that case? Basically `&Object`, `&Basic`, `&Identifiable` and `|Null` can be dropped from any Java signature (outside of boxing for the latter).

**Comment by tombentley** [comment]
Yeah, `simplifyType()` was the first thing I reached for, but I wanted to understand why it didn't *already* simplify `T&Basic` to `T`, because that seems like a no-brainer.

**Comment by FroMage** [comment]
Never had to?
