### ISSUE TITLE
error calling constructor of member class of nested anonymous class

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2084]
```ceylon
class ClassContainer(){
    shared object memberObject {
        shared class Ctor {
            shared new Ctor() {}
            shared new Other() {}
        }
    }
}

ClassContainer.\ImemberObject.Ctor ctor 
        = ClassContainer().memberObject.Ctor.Other();
```

Results in:

```
Cannot find symbol
  symbol:   variable Ctor$Other
  location: class hello.ClassContainer.memberObject_
```

**Comment by ncorai** [comment]
`ClassContainer.\ImemberObject.Ctor` is pure ugliness. I had hoped at least it would be contained to Java interoperability and the metamodel but this is in plain Ceylon code. Sigh...

**Comment by gavinking** [comment]
@ncorai I have *never once* needed to write code like the above. This is a highly contrived example that doesn't at all reflect the kind of code that people naturally write in Ceylon.

**Comment by FroMage** [comment]
We do have an issue open about that syntax: ceylon/ceylon-spec#1205
