### ISSUE TITLE
`ceylon classpath simple` produces no output

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2093]
* `ceylon classpath simple` produces no output or errors. Previous versions worked with or without the version suffix.
* `ceylon classpath dummy` (bad module name) produces no output. Previous versions reported `ceylon classpath: Module dummy not found in the following repositories:...`
* `ceylon classpath simple/1234` (bad version) reports `Module simple not found...`, but produces a classpath anyway - presumably the Ceylon dist classpath. Previous versions reported:

```
$ ~/Dropbox/work-temp/ceylon-201503xx/bin/ceylon classpath simple/1234
ceylon classpath: Version 1234 not found for module simple
Try one of the following versions: 1.0.0
```

**Comment by FroMage** [comment]
Fixed, but looking at history, I can't find at what point in time it reported what you show here…
