### ISSUE TITLE
ceylondoc: expand/collapse hierarchy too hard to click

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2097]
This is a little picky, but:

* Go to the `ceylon doc` page for `Annotated`, for example.
* Click the *Subtype hiararchy* tab
* Try to collapse/expand the hierarchy of `AnnotatedDeclaration`

The little arrow/triangle next to `AnnotatedDeclaration` is really hard to click because the clickable area is only a few pixels wide. The reason seems to be the icon for an enumerated type, which seems to block the click from propagating to the `<span>` which toggles the collapse/expand.

(I initially thought this functionality was *broken* I was finding it so difficult to find the clickable area)

**Comment by thradec** [comment]
Done.
