### ISSUE TITLE
ceylondoc: ceylon.collection::TreeSet and ceylon.collection::TreeMap processing error

### ISSUE THREAD

**Issue by LisiLisenok** [ceylon/ceylon-compiler#2098]
Result of doctool processing:

error [argument must be assignable to parameter 'compare' of 'TreeSet'': 'Comparison(Integer, Integer)' is not assignable to 'Comparison(Integer, Integer)(Integer, Integer)']

The code compiles ok. If remove TreeSet from code, doctool successfuly generates documentation

code, where doctool fails:

"documentation to Foo"
shared class Foo()
{
	"sorted set of items"
	shared TreeSet<Integer> items= TreeSet<Integer>( (Integer first, Integer second) => first <=> second );
}

**Comment by tombentley** [comment]
This works for me. (I did have to add a type argument list `shared TreeSet<Integer> items= ...`).

Which version of Ceylon were you using @LisiLisenok?

**Comment by LisiLisenok** [comment]
version 1.1.0
There was type argument list in origin.
But ceylon doc (documentation compiler) showed the error above. OS Windows if it is important

**Comment by tombentley** [comment]
The bug must have been fixed during development of 1.2 then. Thanks for reporting.
