### ISSUE TITLE
Erroneous annotations not found by javac

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2100]
```ceylon
import ceylon.language.meta.declaration {
    FunctionDeclaration
}

shared annotation class A() satisfies OptionalAnnotation<A,FunctionDeclaration> {}
shared annotation class B() extends A() {}

shared annotation B b() => B();

b
shared void run() {
    print("Hello, World!");
}
```

Three errors on `A` and `B` (2× must be final; must directly extend `Basic`) are expected; however, there are two additional errors:

> source/tmp/run.ceylon:8: error: cannot find symbol
```ceylon
shared annotation B b() => B();
       ^
```
  symbol:   class B
  location: package tmp
source/tmp/run.ceylon:10: error: cannot find symbol
```ceylon
b
^
```
  symbol:   class B$annotation$
  location: package tmp

As always, [generated code](https://gist.github.com/lucaswerkmeister/efd8d1fa6d09110fadeb) (*not* `@noanno`’d for once ;) ). As you can see, `A` and `B` didn’t get generated, but `b` (`@AnnotationInstantiation(arguments = {}, primary = .tmp.B.class`) and `run` (`@.tmp.B$annotation$`) still refer to `B`.

**Comment by tombentley** [comment]
This is basically the same as #1637: At the places we try to use `B` we don't know that we decided not to generate it because it had errors.
