### ISSUE TITLE
ceylon doc: package and module literals don’t work in see annotations

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2104]
```ceylon
see (`package tmp`, `module tmp`)
shared void run() {}
```
results in

> **See also**

```ceylon
see (`function min`, `package tmp`, `value empty`, `module tmp`, `function max`)
shared void run() {}
```
results in

> **See also** `min`, `empty`, `max`

Package and module literals are apparently simply skipped over.

(This only happens in the special `see` annotation; it works fine in custom annotations, even with the nameless `` `package` `` syntax.)

**Comment by tombentley** [comment]
@thradec could you look at this one please?

**Comment by thradec** [comment]
Done.

**Comment by lucaswerkmeister** [comment]
I get `package null` (in red) using the `` `package` `` syntax.

**Comment by thradec** [comment]
<code>\`package\`</code> is syntax for current package?

**Comment by lucaswerkmeister** [comment]
Yep.

**Comment by thradec** [comment]
ups, something new each day :-)
