### ISSUE TITLE
Ceylondoc support for class/interface literals without explicit name

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon-compiler#2106]
see #2104

**Comment by FroMage** [comment]
Looks like this was closed in b96bf5b95068514031c3ac360c684f33dee94e5a

**Comment by thradec** [comment]
reopen, it isn't fixed yet

**Comment by FroMage** [comment]
So what does that commit do then?

**Comment by thradec** [comment]
it fixes only package and module literals

**Comment by FroMage** [comment]
Oh wait, we can have `` `class` ``? I didn't know :)

**Comment by FroMage** [comment]
OK then, sorry my bad.

**Comment by gavinking** [comment]
> I didn't know :)

The irony is, neither did I. I had to check.

And this is a feature you requested and I implemented.

On a plane one day.

**Comment by thradec** [comment]
> I didn't know :)

it seems only @lucaswerkmeister, knew it :-)

**Comment by FroMage** [comment]
Would you have time for that or shall I reschedule for the next release?

**Comment by FroMage** [comment]
Moving to 1.3.

**Comment by thradec** [comment]
It took a while, but it should be done.

**Comment by lucaswerkmeister** [comment]
cool, thanks!

**Comment by FroMage** [comment]
Thanks!
