### ISSUE TITLE
audit all uses of Character.toLowerCase()/isLowerCase()/toUpperCase()/isUpperCase()

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2108]
There are various places where the backend does case-related stuff with `char`s instead of codepoints. We need to find and fix them all.

**Comment by tombentley** [comment]
Audited.

**Comment by gavinking** [comment]
Thanks!

On Wed, Apr 8, 2015 at 1:45 PM, Tom Bentley <notifications@github.com>
wrote:

> Closed #2108 <https://github.com/ceylon/ceylon-compiler/issues/2108>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2108#event-276146660>.
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
