### ISSUE TITLE
shortcut method refinement with =

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2120]
This code:

```ceylon
interface X {
    shared actual default 
    Boolean equals(Object that) 
            => this==that;
}

class Z() satisfies X {
    equals = (super of X).equals;
}
```

Results in:

```
Incompatible types
  required: demo.X
  found:    demo.X$impl
```

**Comment by FroMage** [comment]
Funny thing is if I do:

```ceylon
class Bug2120Z2() {
    equals = super.equals;
}
```

I get:

```
Bug2120.ceylon:34:ERROR:inherited member may not be used in initializer of 'Bug2120Z2': 'equals' is inherited from 'Identifiable'
```

So is it meant to be legal or not?

**Comment by gavinking** [comment]
Well, that's correct according to the rules. OTOH, it looks like the rule could be relaxed in this very particular case.

**Comment by gavinking** [comment]
@FroMage You can open an issue against the typechecker, if you like.

**Comment by gavinking** [comment]
OK, now I see. There definitely is an inconsistency, but both should be allowed.

**Comment by gavinking** [comment]
I opened ceylon/ceylon-spec#1282.

**Comment by gavinking** [comment]
Oops, I was wrong. Now both cases are disallowed. I got it wrong, and this was really a bug in the typechecker. Sillyme, sorry for wasting your time.

**Comment by FroMage** [comment]
Well, it was not a waste of time because the same bug occured in super method references too, so I still had to fix it.
