### ISSUE TITLE
optimize "x in min..max" for ranges of integers and characters

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2129]
The expression `x in min..max` should produce exactly the same Java as `min <= x <= max`, as long as `x`, `min`, and `max` are all of type `Integer`.

**Comment by tombentley** [comment]
Except the span might be descending, so we'll have to use a `let` an evaluate with the endpoints reversed too.

**Comment by gavinking** [comment]
@tombentley Ah yes, very good point, I missing that.

**Comment by gavinking** [comment]
P.S. Oh and the same optimization is needed for measures: `x in min:size` means `x <= min < min+size`.

**Comment by gavinking** [comment]
Oh and the optimization also makes sense for `Character`.

**Comment by quintesse** [comment]
Wouldn't this kind of optimization be perfect for something that could be applied to the tree itself?
Hard-coding this at the level of the code generator just seems to low-level and in this case the JVM and JS backends could most likely share the optimizations.

**Comment by tombentley** [comment]
What ought to happen when `min+size` overflows?

**Comment by gavinking** [comment]
> Wouldn't this kind of optimization be perfect for something that could be applied to the tree itself?

How many times do I have to explain that we have an IDE and messing with the tree is something _we therefore never do_.

**Comment by gavinking** [comment]
> What ought to happen when `min+size` overflows? 

`OverflowException`. Use `Integer.neighbour()` to do the addition.

**Comment by quintesse** [comment]
No, I was actually referring to creating a *new* tree, but we'd still be stuck with how to display any errors. There's need to be some way to map them back to the original tree. (And no of course I'm not suggesting we'd have 2 complete copies, they'd need to share structures)

And really, **everybody** does optimizations that way. Forcing us to always hard-code this into our low-level code generators is making our code far too unwieldy.

**Comment by gavinking** [comment]
@quintesse "everybody" does it that way because they don't have IDEs, and because they generate bytecode or machine code _directly from their AST_. We already have a separate transformation step which transforms to a different (Java) AST. And it's better to do it there where we can take advantage of optimizations which simply can't be done at the level of Ceylon->Ceylon transformation.

**Comment by gavinking** [comment]
Thank Tom! That was quick :)

**Comment by tombentley** [comment]
Anything to avoid thinking about s11n.

**Comment by gavinking** [comment]
haha

**Comment by tombentley** [comment]
Just to note that although the generated code looked good it was actually pants. We now have runtime tests for this and the behaviour of the optimized version should now be the same as the unoptimized version even in overflow cases.

I suppose I should support byte ranges too though.
