### ISSUE TITLE
Allow multiple source directories in the `ceylon-compiler` ant task

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#2131]
It seems the ant task doesn't allow adding several source directories.
Maybe it should provide `<src>` and `<resource>` sub-tags for this case.

**Comment by FroMage** [comment]
@quintesse you know how to do that? I tried but failed to find how to do this.

**Comment by quintesse** [comment]
Yeah, I think so, I'll assign it to me.

**Comment by FroMage** [comment]
Thanks.

**Comment by FroMage** [comment]
Tako, since you are the only one with a clue how to fix this, and that it should be a 20 minutes job, you have until tomorrow to fix it OR ELSE!!!!!

I can't SEE this fucking issue anymore and I don't know how to fix it, it's killing me :(

**Comment by quintesse** [comment]
:)

**Comment by quintesse** [comment]
Done

**Comment by quintesse** [comment]
Oh and BTW it was always possible to add multiple directories by using a path separator, eg:

    <ceylon-compile src="source:test-source">

**Comment by FroMage** [comment]
Thanks!
