### ISSUE TITLE
model loader does not set the deprecated property of classes or functions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2136]
The model loader never calls `setDeprecated()`, which means that we never see any warnings for deprecated elements from binary archives!

**Comment by FroMage** [comment]
What, you add that property at the end of 2013 and you expect us to already know about it?!?!?! ;) We did set the deprecated annotation, though.

**Comment by FroMage** [comment]
Done.

**Comment by gavinking** [comment]
Thanks!
