### ISSUE TITLE
StackOverflowError when compiling generics with defaults

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2138]
StackOverflowError is thrown when compiling:

```ceylon
interface A<out ActualB = B> {}
interface B<out ActualB = B> {}
```

**Comment by gavinking** [comment]
@jpragey this is a bug in the typechecker&mdash;it belongs in `ceylon-spec`.

**Comment by jpragey** [comment]
Moved to https://github.com/ceylon/ceylon-spec/issues/1281, closing.

**Comment by gavinking** [comment]
Thanks.
