### ISSUE TITLE
Make `Declaration.isDeprecated` not require model completion

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2140]
We should be able to move that up out of lazy-loading, as it's making the IDE slow for completions.

**Comment by quintesse** [comment]
Can we do that? Because if possible I'd like the same for `native`, but i thought the fact that it came from an annotation would make that impossible?

**Comment by FroMage** [comment]
Sure we can, we special-case it. We can read annotations without lazy-loading, as long as we don't need to access any model element.

**Comment by quintesse** [comment]
Ok, cool, could we then perhaps add the handling of `native` in the same manner to this issue?

**Comment by FroMage** [comment]
Sure.

**Comment by FroMage** [comment]
Fixed.
