### ISSUE TITLE
cannot compile trivial annotation type

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2143]
```ceylon
annotation final class X(String name) {}
```

Results in:

    method does not override or implement a method from a supertype

**Comment by gavinking** [comment]
Seems to be the `annotationType()` method:

```java
    @.java.lang.Override
    @.com.redhat.ceylon.compiler.java.metadata.Ignore
    public .java.lang.Class<? extends .java.lang.annotation.Annotation> annotationType() {
        return .demo.X$annotation$.class;
    }
```

Is this class supposed to implement `java.lang.annotation.Annotation`? Because it doesn't....

**Comment by FroMage** [comment]
You need to recompile your language module.

**Comment by FroMage** [comment]
Oh wait, you need to extend annotation no?

**Comment by gavinking** [comment]
§7.2.2:

> Annotation constructors produce instances of annotation types. An annotation 
> type is a class annotated `annotation`. An annotation type may not be a generic 
> type with type parameters. An annotation type must have an empty initializer section.
> 
> _Note: currently every annotation type must be a final class which directly extends Basic in ceylon.language._

**Comment by gavinking** [comment]
The spec has two things:

- _annotation types_, and
- _constrained annotation types_.

And it says:

> The return type of an annotation constructor must be a constrained annotation type...

But the constrained annotation type may itself have members whose type is simply an annotation type.

**Comment by FroMage** [comment]
And you tell me now? I may as well revert my entire changes

**Comment by FroMage** [comment]
> Note: currently every annotation type must be a final class which directly extends Basic in ceylon.language.

That's not true, most extend `Annotation`

**Comment by FroMage** [comment]
So if we can have annotations that do not extend `Annotation` we can't query for them using the metamodel, given the `annotations<A>() given A satisfies Annotation` constraint.

**Comment by gavinking** [comment]
>> Note: currently every annotation type must be a final class which directly extends Basic in ceylon.language.

> That's not true, most extend `Annotation`

`extrends`,  not `satisfies`.

**Comment by FroMage** [comment]
Ah, OK.

**Comment by gavinking** [comment]
> So if we can have annotations that do not extend `Annotation` we can't query for them using the metamodel, given the `annotations<A>() given A satisfies Annotation` constraint.

Read properly what I'm telling you. *Members* of an annotation don't need to satisfy `Annotation`. The type of the _whole annotation_ does!

**Comment by FroMage** [comment]
Pfff… and we have exactly zero tests for that in the language module or in the JVM backend. I suppose I can make them either implement `j.l.a.Annotation` discreetly or not at all…

**Comment by gavinking** [comment]
Yes, I guess they do need to implement `j.l.a.A`. I suppose Java enforces that.

**Comment by FroMage** [comment]
Fixed, I removed that method since it does not implement `j.l.a.Annotation` and I don't see the point in making it implement it because it will fuck up more things that it's worth (as in, `is c.l.Annotation` will suddently return true when it should not).
