### ISSUE TITLE
import error when compiling to both backends

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2146]
In the IDE, with both "Compile project for/to" options enabled, I get:

```ceylon
import com.vasileff.ceylon.xmath.whole {
    wholeNumber // ok
}

import com.vasileff.ceylon.xmath.long {
    longNumber // backend error
    // Cannot import Java declarations in Javascript
}

shared void run() {
    value x = longNumber(1); // backend error
    // Cannot call Java declarations in Javascript
}
```

There are no errors using the CLI or in the IDE when just one backend is enabled.

I suspect this may have to do with escaping of the Java reserved word `long`.

**Comment by tombentley** [comment]
I'm not sure this is really a compiler bug. It seems like it better belongs in ceylon-ide-eclipse. 

We have compiler tests for sources in packages whose names include a Java reserved word component.

@davidfestal any thoughts about this?

**Comment by davidfestal** [comment]
@jvasileff :  to test again I assume I should clone your last `xmath`project ?
Or could you check that with everything pulled this still happens ?

**Comment by jvasileff** [comment]
Sure, I can try it out in a bit.



On Jun 18, 2015, at 10:40 AM, David Festal <notifications@github.com<mailto:notifications@github.com>> wrote:


@jvasileff<https://github.com/jvasileff> : to test again I assume I should clone your last xmathproject ?
Or could you check that with everything pulled this still happens ?

-

**Comment by anettan** [comment]
mailto:notifications@github.com>> wrote  again I assume I should clone your last xmathproject ?

**Comment by jvasileff** [comment]
Moved to https://github.com/ceylon/ceylon-ide-eclipse/issues/1379
