### ISSUE TITLE
Generate error on ambiguous use of annotation

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2154]
For:

```ceylon
import javax.inject { inject }

class Application() {
    shared late inject String repository; 
}
```
the `inject` annotation is applied to the getter, and a warning is produced:
```
Ambiguous annotation target: inject could be applied to several targets, use one of inject__FIELD, inject__GETTER, inject__SETTER to disambiguate
```

I believe this should be an error. It's unclear from the code how the ambiguity will be resolved, and it would be impossible for the compiler to infer the correct application.

**Comment by gavinking** [comment]
@jvasileff I don't think I agree. In your example, the current behavior is actually _perfectly fine_. Indeed, I can't think of any annotation that could apply to a field or getter/setter where it would matter which.

**Comment by jvasileff** [comment]
@gavinking I don't follow. Surely you can't perform injection on a getter? The correct code in this example is:

```ceylon
class Application() {
    shared late inject__SETTER String repository; 
}
```

**Comment by gavinking** [comment]
OIC. Damn. OK, that _does_ suck.

I need to think about it.

**Comment by gavinking** [comment]
This issue will be solved by https://github.com/ceylon/ceylon.language/issues/681 together with https://github.com/ceylon/ceylon-compiler/issues/2160.

Let's move the discussion there, and @jvasileff would you check that my proposal really solves your problem?

I'm closing this one.

**Comment by jvasileff** [comment]
Currently, for:

```ceylon
    late inject // (same with shared)
    Environment environment;
```
you get a warning:
```
Ambiguous annotation target: inject could be applied to several targets, use one of inject__FIELD, inject__GETTER, inject__SETTER to disambiguate
```
Is it correct that this will become an error like:
```
Annotated program element does not satisfy annotation constraint: ValueDeclaration is not assignable to FunctionDeclaration|ReferenceDeclaration
```
(BTW - Trying to simulate this in pure Ceylon today results in  *`ReferenceDeclaration`* is not assignable to ..., even for  `shared String something = "";`?)
