### ISSUE TITLE
Multiple constructors causes weirdness for later closures

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-compiler#2164]
Compiling this:
```ceylon
shared class Bar {
    shared new() {}
    shared new A() {}

    value local = {for (x in [1, "str"]) if (is Integer x) x};
}
```

gives this:
```
source/tmp/tmp.ceylon:5: error: local variable x$1 is accessed from within inner class; needs to be declared final
    value local = {for (x in [1, "str"]) if (is Integer x) x};
                                             ^
source/tmp/tmp.ceylon:5: error: unreachable statement
    value local = {for (x in [1, "str"]) if (is Integer x) x};
```

**Comment by sadmac7000** [comment]
Removing either constructor fixes the issue.

**Comment by lucaswerkmeister** [comment]
[generated code](https://gist.github.com/lucaswerkmeister/bdb25e7f1d9b0cdd7701), `@noanno`’d

**Comment by sadmac7000** [comment]
Looking at the generated code, it looks like `x` &co. just need `final` like the error says. If I knew the compiler code better I could write the patch.

**Comment by lucaswerkmeister** [comment]
I think comprehensions are done in [`ExpressionTransformer`, L5160-5621](https://github.com/ceylon/ceylon-compiler/blob/4e882ad7222a54d64f5e194453ff550c95b835a4/src/com/redhat/ceylon/compiler/java/codegen/ExpressionTransformer.java#L5160-L5621).

Not sure where the error’s coming from, so I can’t offer more advice right now…

**Comment by lucaswerkmeister** [comment]
If either constructor is removed, the generated code for the remaining one is identical to what I posted above. But `x$1`, the variable from the error message, is a field of an anonymous class local to the constructor. So I’m confused… is javac compiling them into the same class somehow?
