### ISSUE TITLE
Add `start` *and* `end` positions when building Javac `Diagnostics` from AST `Node` errors

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#2166]
This will allow the IDE to show backend error markers on the whole node width (currently we have only the start position, so that the error marker underline annotation is one-char-wide, which is *very* ugly).
Additionally, the AST `Node` provides this information (this is what we use in the IDE to retrieve start end offset of typechecker error markers)

**Comment by gavinking** [comment]
Thanks.

On Thu, May 21, 2015 at 2:23 PM, David Festal <notifications@github.com>
wrote:

> This will allow the IDE to show backend error markers on the whole node
> width (currently we have only the start position, so that the error marker
> underline annotation is one-char-wide, which is *very* ugly).
> Additionally, the AST Node provides this information (this is what we use
> in the IDE to retrieve start end offset of typechecker error markers)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2166>.
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
