### ISSUE TITLE
Union on Method/Function has type Nothing and WrongMethodTypeException

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon-compiler#2168]
OK, this appears to be caused by nullable enumeration.

Given the following Ceylon code (standalone)  - 
```ceylon
class MethodFunction( produce) {
    
    shared Method<Anything, Boolean?, [List<String>]> |
            Function<Boolean?, [List<String>, String]> produce;
}

class Call(MethodFunction mf) {
    shared Boolean? produceRoute(List<String> c, MethodFunction r) {
        if ( is Method<Anything,Boolean?,[List<String>]> producer = r.produce) {
            return producer("")(c); 
        }
        else if ( is Function<Boolean?,[List<String>, String]> producer = r.produce) { 
            return producer(c, "");                    
        } else {
            return null;
        }
    }
}
```

1. On restoring from Git, compiles fulllyl with warning `Expression has type Nothing` on both `producer(` calls and runtime error `java.lang.invoke.WrongMethodTypeException: expected (Object,Object)Object but found ()Object` :
2. On subsequent project cleans, only partially compiles and gives back end error `Variable producer$301 might not have been initialized` and the variable does not exist due to partial compile

**Comment by FroMage** [comment]
I can fix the second error about initialisation, but how can I reproduce the first one?

**Comment by FroMage** [comment]
I pushed a fix for the initialisation error. Let me know if you still run into the first issue?

**Comment by FroMage** [comment]
I'm going to close this. If you can still reproduce it, feel free to reopen.
