### ISSUE TITLE
disappearing errors relating to native imports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2173]
@quintesse @davidfestal There's something deeply wrong with this error:

    Native import for cross-platform module (mark either the module or the import as native)

In the IDE at least it randomly appears and disappears, disappearing more than it appears. At first I thought the error was completely missing but now I realize that it appears and disappears from build to build.

**Comment by sgalles** [comment]
I had noticed something like this but I could not pinpoint it. Now I think I have something.
* create a dual JVM+JS Ceylon project
* create a module
* import `ceylon.file` in the module. You get the expected `native` error.
* Go to the ceylon settings and deactivate the JS builder. The error doesn't go away.

**Comment by davidfestal** [comment]
but it seems to me that the error shouldn't disappear in this case.

**Comment by sgalles** [comment]
Ha. OK I misunderstood the feature :) So I'll try to check out when I had witnessed the opposite behavior. Thanks.

**Comment by gavinking** [comment]
Thanks!!

On Mon, May 25, 2015 at 3:59 PM, David Festal <notifications@github.com>
wrote:

> Closed #2173 <https://github.com/ceylon/ceylon-compiler/issues/2173> via
> ceylon/ceylon-ide-eclipse@3a5dba3
> <https://github.com/ceylon/ceylon-ide-eclipse/commit/3a5dba306825e3e650effe172fcdd91d7d03b1cd>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2173#event-313054402>.
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
