### ISSUE TITLE
implement singleton constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2176]
Whenever you guys feel like it, it should be easy to implement support for https://github.com/ceylon/ceylon-spec/issues/1129.

**Comment by tombentley** [comment]
Pushed some initial support for this to the `spec1129` branch. Still to do:

* [ ] support for singletons constructors for member classes of interfaces and local classes
* [ ] model loading
* [ ] delegation (if singleton ctors support delegation...?)
* [ ] use of singleton constructors as a annotation target (including interop)
* [ ] investigate/fix of interop `enum` switching

But there should be enough to play with.

**Comment by gavinking** [comment]
Awesome!

Singleton constructors should eventually support delegation to partial constructors. But we don't need to support that until we have time to implement it. The typechecker doesn't yet support it. So let's get the rest working first!

**Comment by gavinking** [comment]
@tombentley this code:

```ceylon
class MyPoint {
    shared Float x;
    shared Float y;
    shared new origin {
        x = 0.0;
        y = 0.0;
    }
    string => "(``x``, ``y``)";
}

void runWithPoint() {
    print(MyPoint.origin);
}
```

Gives me:

    GetOrigin() has private access in calendar.MyPoint

**Comment by tombentley** [comment]
Should be fixed now.

**Comment by gavinking** [comment]
Cool, thanks, let's see.

**Comment by tombentley** [comment]
I think I'm done on this for now (until such time as we actually decide to merge this stuff). At which point:

* [ ] Fix interop `enum` support
* [ ] Need metamodel support for these things.
* [ ] Need more tests, for example with singletons listed in `of` clauses

**Comment by gavinking** [comment]
@tombentley I'm in the IDE, attempting to compile this:

```ceylon
class Point {
    shared Float x;
    shared Float y;
    shared new origin {
        x = 0.0;
        y = 0.0;
    }
```

It passes the typechecker, but the backend gives me:

```
The Ceylon Java backend compilation failed
  with a throwable : com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.redhat.ceylon.compiler.java.metadata.Enumerated not found
```

**Comment by gavinking** [comment]
On the command line I get:

```
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:522)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:504)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.redhat.ceylon.compiler.java.metadata.Enumerated not found
```

**Comment by tombentley** [comment]
You pulled the spec*Whatever* branch of ceylon.language and rebuilt everything?

**Comment by gavinking** [comment]
aaah you have a branch of `c.l` now too.

**Comment by tombentley** [comment]
I [told you that](https://gitter.im/ceylon/user?at=55716b76777c17d06a140839), though admittedly not here on the issue.

**Comment by gavinking** [comment]
@tombentley this class:

```ceylon
class Bool {
    shared new true {}
    shared new false {}
}
```

Results in:

```
Cannot find symbol
  symbol:   variable true
  location: class calendar.Bool
```

Renaming to `truex` and `falsex` solves the problem. Some name-mangling issue, I imagine.

**Comment by gavinking** [comment]
Also:

```ceylon
import calendar {
    Bool {
        t=true_,
        f=false_
    }
}

Bool bt = t;
```

Results in:

```
compiler bug: calendar::Bool.true_ was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4693)
```

**Comment by gavinking** [comment]
@tombentley finally, static refs to singleton constructors of member classes, for example, `Outer.Inner.instance`, don't seem to be working.

**Comment by sgalles** [comment]
I'm not sure, does this belong to this issue ?
this code
```ceylon
import foo{
	Foo {bar}
}

class Foo{
	shared new bar{}
}

shared void run(){
	Foo f = bar;
	print(f);
}
```
* compiled with the java backend : *NPE*
* executed with the JS backend outputs `<null>`

Or should I open two issues ?

**Comment by FroMage** [comment]
Yes please. This issue is about something which is merged no ? Why is it 1.3 then?

**Comment by sgalles** [comment]
OK @FroMage 
So we have
* https://github.com/ceylon/ceylon-compiler/issues/2262
* https://github.com/ceylon/ceylon-js/issues/611

**Comment by FroMage** [comment]
@tombentley have the last comments reported by @gavinking been fixed already or not? If yes then why is this issue still open?

**Comment by tombentley** [comment]
I don't think they have, yet. I'll do those next.

**Comment by FroMage** [comment]
Oh, OK thanks.

**Comment by tombentley** [comment]
This is now done.
