### ISSUE TITLE
Constructors and return (and throw)

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2181]
We need to implement this https://github.com/ceylon/ceylon-spec/issues/1288

**Comment by tombentley** [comment]
This boiled down to changing how we transform `return` when in a constructor (which is followed by initializer statements) to something which doesn't *actually* return but just does a local jump (because those following initializer statements will be transformed to local statements). The local jump is implemented as a labelled `break` within a `do/while(false)`. That trick only works because constructors can only use the "nullary" variant of `return`. But it seems to work.

**Comment by gavinking** [comment]
Excellent!
