### ISSUE TITLE
shortcut refinement with multiple parameter lists

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2182]
```ceylon
interface FooBaz {
    shared formal String foo()();
}
class Baz() satisfies FooBaz {
    foo() => () => "hello";
}
```

I get:

    Compiler bug: Index: 1, Size: 1 at java.util.ArrayList.rangeCheck(ArrayList.java:638)

**Comment by FroMage** [comment]
If this is hard to implement (it could be we don't have the machinery for this) then we'll move it to 1.3.
