### ISSUE TITLE
NPE for incomplete constructor delegation

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2186]
When this (broken) code is compiled
```ceylon
class Foo{ 
    shared new Bar(){}
    shared new Baz() extends Bar{} 
}
```
`compiler bug: null at com.redhat.ceylon.compiler.java.codegen.CeylonVisitor.visit(CeylonVisitor.java:146)`

**Comment by FroMage** [comment]
Done.
