### ISSUE TITLE
NPE for several method ref of Iterable

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2198]
For instance this code
```ceylon
Anything a = {}.map;
```
compiled
```
compiler bug: null at com.redhat.ceylon.compiler.java.codegen.AbstractTransformer.makeReifiedTypeArguments(AbstractTransformer.java:4943)
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:324)
```
FTR same thing with  `collect`.

**Comment by tombentley** [comment]
The Ceylon parse tree includes this:

    |  |  |  |  +  [QualifiedMemberExpression] (1:19-1:24) : <Result> => {Result*}(Result(Nothing)) : {}.map<unknown> : function Iterable<Element,Absent>.map<Result>(Result collecting) => Iterable<Result,Absent>

The `map<unknown>` makes me think this might be a typechecker problem @gavinking? This a type function, isn't it. So I suppose we need a "not supported on the JVM right now"-type error.

**Comment by gavinking** [comment]
@tombentley yes, right, that's on my todo list. If you see a type like this:

    <Result> => {Result*}(Result(Nothing))

It's not supported yet. I need to make that an error.

**Comment by FroMage** [comment]
Moved to typechecker.
