### ISSUE TITLE
line numbers for switch

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2203]
Stepping through a `switch` in the debugger is a *terrible* experience because the line numbers jump about for each test done (and they're not always done in lexical order). The user probably doesn't care to step through each test being performed (for their pov there's no code being executed an `is` just happens by majik), the just want to step from the `switch` expression to the matched `case`.

**Comment by tombentley** [comment]
This is not as simple as it looks. We have no API to express "actually ignore all the position updates until I tell you otherwise" (which is what we need I think). And then there's the small matter of arranging the telling otherwise.

**Comment by tombentley** [comment]
Fixed, and debugging through a `switch` is now a lot more natural, imo, you just from the `switch` straight into the matched `case` block.

**Comment by gavinking** [comment]
Excellent!
