### ISSUE TITLE
NPE in IDE for reserved keyword used as member class name

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2207]
This code
```ceylon
class Foo(){
	class let(){}
}
```
in the IDE
`compiler bug: null at com.redhat.ceylon.compiler.java.codegen.Naming.escapeClassName(Naming.java:1151)`

**Comment by FroMage** [comment]
Seems to be an IDE bug because this doesn't parse on the CLI so I can't reproduce, I don't get as far as that NPE. @sgalles can you reproduce on the CLI?

@davidfestal WDYT?

**Comment by sgalles** [comment]
@FroMage No, it was an IDE bug only.
And now...it seems that I'm not able to reproduce the issue with the IDE either...
Well I guess that somehow something fixed this error in the meantime. I can close the issue I suppose.

**Comment by FroMage** [comment]
Thanks
