### ISSUE TITLE
Incorrect erasure with union type argument to constrained type param and default argument

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2208]
```ceylon
shared abstract class Sup() {}
shared class Sub1() extends Sup() {}
shared class Sub2() extends Sup() {}

shared interface I<T,S>
        given S satisfies Sup {
    shared formal T toT(S s = nothing);
}

shared object string satisfies I<String,Sub1|Sub2> {
    toT(Sub1|Sub2 s) => "";
}
```
> source/tmp/run.ceylon:10: error: `string_` is not abstract and does not override abstract method `toT(Sup)` in `I`
```ceylon
shared object string satisfies I<String,Sub1|Sub2> {
^
```
error: `toT$s()` in `string_` cannot implement `toT$s()` in `I`
  return type `Object` is not compatible with `Sup`
  where `S` is a type-variable:
    `S extends Sup` declared in interface `I`

The error vanishes if you do any of the following:
- remove the `given S satisfies Sup` constraint from `I`
- remove the default argument from `toT`
- remove the union type from `string`’s type argument to `I` (use `Sup`, `Sub1` or `Sub2` instead)
- add an `@noanno` compiler annotation to `string` itself – this only removes the second error (“cannot implement”), the first (“does not override”) remains; other `@noanno`s have no such effect

The error remains if you do any of the following:
- implement `string.toT` as a full function definition (`shared actual `etc.)
- implement `string.toT` as a function reference (`toT = toString;`)
- remove the default argument from `toT.s` and instead add a second defaulted parameter (e. g. `Null n = null`); the error looks a bit different in that case (“`toT$n` cannot be applied to given types”), but it’s still `Sup` vs. `Object`

As always, [generated code](https://gist.github.com/lucaswerkmeister/8ea52081dd0104c5759d), `@noanno`’d (except for `string`, see above). If you go through the gist’s [history](https://gist.github.com/lucaswerkmeister/8ea52081dd0104c5759d/revisions), you can see how I gradually simplified it further and further. Perhaps you want to test the earliest and largest version manually when you think you’ve fixed the issue, just in case I oversimplified it.

**Comment by FroMage** [comment]
Ah, interesting, perhaps it's easy to fix. We already have code for that for parameters, perhaps we're just not using it for default value methods.

**Comment by FroMage** [comment]
Of course it's not so simple. In fact it's pretty amazing that this thing worked so far.

**Comment by FroMage** [comment]
OK, two days in, I fixed this one. Now let's see how many others I broke.

**Comment by FroMage** [comment]
65 test failures. Man, I should have left this issue for 1.3 :(

**Comment by lucaswerkmeister** [comment]
Well I had about 50 on master yesterday…

**Comment by FroMage** [comment]
What? That's not normal.

**Comment by lucaswerkmeister** [comment]
Okay, I’ll run them again. Because it’s not hot enough in my room yet, I need to heat it up some more with my CPU.

**Comment by lucaswerkmeister** [comment]
50 failures, 23 errors.

**Comment by lucaswerkmeister** [comment]
several of the failures are

> Compilation failed ERROR: frontend: 25: cannot find module artifact org.hibernate.javax.persistence:hibernate-jpa-2.1-api-1.0.0.Final(.car|.jar) - dependency tree: com.redhat.ceylon.compiler.java.test.metamodel/123 -> org.hibernate.javax.persistence:hibernate-jpa-2.1-api/1.0.0.Final

**Comment by FroMage** [comment]
Can you open another issue for that please?

**Comment by FroMage** [comment]
Two days in, still no end in sight, but there's (slow) progress.

**Comment by lucaswerkmeister** [comment]
> Can you open another issue for that please?

Okay, I’ll just test again to make sure the errors are still there.

**Comment by lucaswerkmeister** [comment]
#2224

**Comment by FroMage** [comment]
And that's a wrap. Three days, man. Last time I ever fix an erasure bug.

**Comment by gavinking** [comment]
Yay!

On Fri, Jul 3, 2015 at 1:07 PM, Stéphane Épardaud <notifications@github.com>
wrote:

> And that's a wrap. Three days, man. Last time I ever fix an erasure bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2208#issuecomment-118316948>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org

**Comment by lucaswerkmeister** [comment]
> And that's a wrap. Three days, man.

Jesus christ. Thanks man. I’m glad I [apologized in advance](https://gitter.im/ceylon/user?at=5585d8ff9a24b6e368d44e36) for finding this…

> Last time I ever fix an erasure bug.

I’m pretty sure I’ve heard that before.
