### ISSUE TITLE
constructor interop

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2225]
Now Ceylon has constructors we should re-work interop for using overloaded java constructors. The model loader needs to generate abstractions of the default constructor, and the old abstractions we added for classes need to be removed.

**Comment by FroMage** [comment]
Those have no name, though, so how would it work?

**Comment by tombentley** [comment]
We generate abstraction constructors of the default constructor. Java classes would only have default constructor(s).

**Comment by FroMage** [comment]
Ah OK I see.

**Comment by FroMage** [comment]
Does the typechecker already know how to deal with those?

**Comment by tombentley** [comment]
Sorry, I don't know if its handling is specific to `Class` or abstracted over everything with abstractions.

**Comment by tombentley** [comment]
The bulk of the work should be "just" refactoring the model loader so it generates abstraction constructors instead of abstraction classes. That should actually simplify the model loader slightly.

**Comment by FroMage** [comment]
So I've done _something_, but I can't really test it because the typechecker doesn't seem to understand overloaded constructors.

**Comment by gavinking** [comment]
Yeah I never tested the overloading stuff work for constructors, but I don't imagine it's a very difficult change.

**Comment by FroMage** [comment]
ATM I'm trying to make `Class.isAbstraction()` mean that it has overloaded constructors, and then fix the lookups to look for constructors rather than classes. Let's see where this leads.

**Comment by FroMage** [comment]
Grr, of course, people assume that if it's an abstraction it has overloads. I bet it'd be just as confusing for me to place the overloaded constructors in there.

**Comment by FroMage** [comment]
So that totally changes how we look for members. Currently we look at the container, find by name and select on signature. Now if we're looking for an overloaded Java constructor we have to recurse into the class to find the matching overloaded constructor. This is starting to smell.

**Comment by FroMage** [comment]
Plus when you're looking for a class and you end up with a constructor that can be weird.

**Comment by gavinking** [comment]
> ATM I'm trying to make `Class.isAbstraction()` mean that it has overloaded constructors

Waaah? No, that can't be right, can it?

Shouldn't there be a abstraction `Function` that points to a `Constructor` abstraction?

**Comment by gavinking** [comment]
> So that totally changes how we look for members. 

I don't follow.

What you should try to do is make this a special case of method overloading. We already support overloaded `static` methods of Java classes. Try to make it look as much like that as possible.

**Comment by FroMage** [comment]
Mmm, I didn't know where to put the overload because both `Function` and `Constructor` support overloads. What's the point of having them both?

> I don't follow.

Well, before, if we were looking for constructor `Foo` with signature `X` we looked in the package and filtered by name and signature and found the right `Class`. Now we have to also look _inside_ classes if they have overloaded constructors, to find the right constructor.

**Comment by gavinking** [comment]
OIC, you're dealing with default constructors here, not named constructors. Yeah, um, not sure.

**Comment by FroMage** [comment]
Yes, they don't have names. I could add them to the container (package) but that'd mean we'd have one `Class` and several `Constructor` with the same name in that scope. That'd also be weird.

**Comment by FroMage** [comment]
Rather, they have the same name as the class, but we refer to them with just the class name, not via `Foo.bar`.

**Comment by FroMage** [comment]
We could force people to refer to them as if they were Ceylon constructors like `Foo.foo` but that seems a regression in friendliness.

**Comment by gavinking** [comment]
> but that seems a regression in friendliness.

Yeah I guess that wouldn't be acceptable.

So what's the solution?

We abandon this?

**Comment by FroMage** [comment]
If it ain't broke…

I mean, it's ugly but it works, and the alternative is ugly too.

Unless it poses an issue wrt extending a Java class from Ceylon, which has overloaded constructors and the Ceylon constructors need to delegate to them?

**Comment by gavinking** [comment]
@FroMage you have looked at the code so I'll have to take your word for it.

**Comment by gavinking** [comment]
> Unless it poses an issue wrt extending a Java class from Ceylon, which has overloaded constructors and the Ceylon constructors need to delegate to them?

Well, I haven't tested it, but I don't see why that should be a problem.

**Comment by FroMage** [comment]
OK, let's give up if it doesn't buy us anything.
