### ISSUE TITLE
Better assertion messages

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2235]
I'd love for `assert(x == y)` (and possibly other operators) to expand to a call to `AssertUtils.equals(Object a, Object b)` (and unboxed) where the error message if it fails would include both operands, because "assertion failed" is pretty useless if I don't know what the operands are.

**Comment by gavinking** [comment]
+1.

**Comment by tombentley** [comment]
This is a dupe of https://github.com/ceylon/ceylon-compiler/issues/1280

**Comment by FroMage** [comment]
Damnit
