### ISSUE TITLE
annotations on LOCAL_VARIABLE might "capture" the variable

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2239]
@tombentley this is motivated by this classical CDI idiom :
```ceylon
class DatabaseProducer() {
    persistenceContext__SETTER
    produces__GETTER
    late EntityManager em;
}
```
This does not compile
```
no target for persistenceContext__SETTER annotation: @Target of @interface PersistenceContext lists [SETTER] but annotated element tranforms to [LOCAL_VARIABLE]
no target for produces__GETTER annotation: @Target of @interface Produces lists [GETTER] but annotated element tranforms to [LOCAL_VARIABLE]
```
To make it compile I must either share `em`, or artificially use `em` in a method of `DatabaseProducer`

**Comment by FroMage** [comment]
Oh, and you can't put the annotation on the field because it's not marked as captured.

Well, should we make every annotated value "captured"? Because that would then also apply to `late` values.

**Comment by jvasileff** [comment]
Isn't `late` pretty much meant for captured values?

**Comment by quintesse** [comment]
What about `variable` and whatever other annotations we can think of in the future? It seems a bit "overzealous" to just capture anything that has just any annotation.

**Comment by jvasileff** [comment]
Does the Ceylon metamodel support accessing non-`shared` members? If not, maybe this should apply to only interop annotations.

**Comment by FroMage** [comment]
It does, if they are captured.

I'm thinking that a compiler annotation to force capturedness may make sense here, no?

**Comment by FroMage** [comment]
Something like:

```ceylon
class DatabaseProducer() {
    persistenceContext__SETTER
    produces__GETTER
    @captured late EntityManager em;
}
```

**Comment by FroMage** [comment]
Actually the order is significant, so this now works:

```ceylon
class DatabaseProducer() {
    @captured
    persistenceContext__SETTER
    produces__GETTER
    late EntityManager em;
}
```

Good enough?

**Comment by sgalles** [comment]
@FroMage Yes, it works for my use case. Thanks !

**Comment by tombentley** [comment]
@FroMage using a compiler annotation like this is an abuse. They were always meant to be just for testing the typechecker and compiler with, never to use in real code. I think we need to find a different way.

**Comment by FroMage** [comment]
I'm fine with an official annotation, if you prefer. At least ATM there's a way to support this.

**Comment by gavinking** [comment]
> using a compiler annotation like this is an abuse. They were always meant to be just for testing the typechecker and compiler with, never to use in real code.

Totally!

> I think we need to find a different way.

+1.

**Comment by tombentley** [comment]
I would prefer, but it seems out of place in the language module, and if it were in ceylon.interop.java, or anywhere else, then the compiler isn't really supposed to know about it. I do think eventually we'll have to let the compiler know about ceylon.interop.java.

**Comment by gavinking** [comment]
> I'm thinking that a compiler annotation to force capturedness may make sense here, no?

I'm not sure this is really necessary. It seems to me unlikely that you want to annotate local variables of the initializer with user-written annotations.

It seems to me that we could assume that fields annotated with user-written annotations are captured.

**Comment by FroMage** [comment]
Where "user-written" means non-language-module annotations?

**Comment by gavinking** [comment]
Yeah.

**Comment by FroMage** [comment]
That doesn't work as well (just tried) because it turns annotated unshared class initialiser parameters into annotated properties, where before they used to be annotated constructor parameters.

OTOH that is already the case with captured class initialiser parameters, so perhaps it's acceptable.

**Comment by gavinking** [comment]
Sounds to me like the previous behavior was very inconsistent. Adding a `shared` annotation affected what kind of Java annotation you could add to the parameter? That's sounds wrong.

**Comment by FroMage** [comment]
OK done.

**Comment by sgalles** [comment]
@FroMage it works, that's neat.
I've stumbled upon this though, with the `suppressWarnings` annotation, in relation with the order of the application of the annotations :

This compiles
```ceylon
entity
shared class Foo(){

	id__FIELD
	generatedValue__FIELD
	suppressWarnings("unusedDeclaration")
	Long? id = null;

}
```
but this does not compile
```ceylon
entity
shared class Foo(){

	suppressWarnings("unusedDeclaration")
	id__FIELD
	generatedValue__FIELD
	Long? id = null; // ERROR not target for id__FIELD/generatedValue__FIELD

}
```

**Comment by FroMage** [comment]
That sounds like a different bug. Let me refile it at https://github.com/ceylon/ceylon-compiler/issues/2252
