### ISSUE TITLE
Ceylon annotation__TARGET not available when Java annotation has empty  @Target and RUNTIME @Retention

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2242]
(FTR I've detected this with https://docs.oracle.com/javaee/6/api/javax/inject/Named.html)

To reproduce :
create this java annotation :
```java
@Retention(value=RetentionPolicy.RUNTIME)
public @interface Baz {}
```
and use in this ceylon code
```ceylon
baz__TYPE
shared class Foo(){} 
```
you get
`function or value does not exist: 'baz__TYPE'`

**Comment by FroMage** [comment]
So the docs say that if `@Target` is not present, all elements should be allowed.

**Comment by FroMage** [comment]
Oh FFS, we have ZERO tests for that feature!!!!

**Comment by FroMage** [comment]
Fixed, and added tests for the `__` prefix thing.
