### ISSUE TITLE
strange error message when `javaClass` is used in annotation parameter

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2245]
This was trying to use http://docs.oracle.com/javaee/6/api/javax/faces/convert/FacesConverter.html

I want to inject in the annotation the `java.lang.Class` that represents `ceylon.language.String`

So I tried
```ceylon
facesConverter{forClass = javaClass<String>(); }
```
but I get this compilation error
`annotation constructor must return a newly-instantiated annotation`
So I guess the error is really that `javaClass` is not a constant, and the error message can be improved.
As a side note, I'm stuck, I don't know how to get the `java.lang.Class` that represents `ceylon.language.String` in this annotation

**Comment by tombentley** [comment]
I think this should work for what you're actually trying to do:

    facesConverter{forClass = `class String`}

But the error message should still be fixed.

**Comment by sgalles** [comment]
Ah ! @tombentley now I'm pretty sure that something does not work with 
```ceylon
facesConverter{forClass = `class String`}
```
Actually at runtime the annotation gets `java.lang.String` instead of `ceylon.language.String`.
Maybe it is on purpose to ease the interop with Java, but I simply don't know how to reference `ceylon.language.String` in the annotation now.

**Comment by tombentley** [comment]
Ah, so yes there is a bug there then, well spotted. 

But I now realise there's a further subtlety affecting this bit of interop and primitive types, given

    import java.lang{JBoolean=Boolean}
    forClass = `class JBoolean`

does that mean `boolean.class` (== `java.lang.Boolean.TYPE`) or `Boolean.class`? They're different things in the JVM. Whichever I chose it to mean, someone is bound to want the other one, at some point.

The only way I can think to solve this right now would be to permit

    import java.lang{Jboolean = \Iboolean}

so we had distinct types for the primitivie type and its box. But allowing that generally would open up a whole Pandoras box of trouble, since primitives are not objects. Still that's another issue.

**Comment by tombentley** [comment]
For the time being I will make this mean `Boolean.class`, since in my experience that's used more often than `boolean.class`/`Boolean.TYPE`.

**Comment by lucaswerkmeister** [comment]
Perhaps a compiler annotation could be used?
```ceylon
import java.lang { JBoolean=Boolean }
facesConverter { forClass = `@primitive class JBoolean`; }
```

**Comment by tombentley** [comment]
Nope, that would be an abuse of compiler annotations, which are intentionally undocumented and unsupported. For interop we need something that is at least part of the language.

I suppose we have a similar problem that `javaClass` can't express `boolean.class` either (or maybe it can't expression `Boolean.class`). But these comments belong in #2246 at least :-)

**Comment by lucaswerkmeister** [comment]
Didn’t we use compiler annotations for something very similar just recently? (Can’t find it right now.)

**Comment by tombentley** [comment]
I hope not!

**Comment by sgalles** [comment]
> Didn’t we use compiler annotations for something very similar just recently? (Can’t find it right now.)

@tombentley @lucaswerkmeister *cough* https://github.com/ceylon/ceylon-compiler/issues/2239#issuecomment-123783887 *cough*
(but I guess that was proposed as a temporary workaround though)

**Comment by lucaswerkmeister** [comment]
That’s the one I meant, thanks :)
