### ISSUE TITLE
compiler bug for class alias delegating to constructor

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2248]
```ceylon
shared class C {
    shared new c() {}
}
shared class D() => C.c();
```
> error: constructor C in class C cannot be applied to given types;
  required: c_
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Created module tmp/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in the compiler.
[…] bla bla please report
com.redhat.ceylon.compiler.CompilerBugException: Bug
        […] snip
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ErrorType cannot be cast to com.sun.tools.javac.code.Symbol
	at com.sun.tools.javac.jvm.Code.emitop2(Code.java:996)
	at com.sun.tools.javac.jvm.Gen.visitNewClass(Gen.java:1728)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1374)
        […] snip

As always, [generated code](https://gist.github.com/lucaswerkmeister/c1c9b610fc9757f33bff), `@noanno`’d.

~~Note: I think the spec currently doesn’t actually bless class aliases delegating to constructors, so depending on how ceylon/ceylon-spec#1388 is resolved, this bug might turn out to be invalid.~~

**Comment by lucaswerkmeister** [comment]
Per ceylon/ceylon-spec@f0efa7ddbf139688a004bdce713b107a07bd9703, delegation to constructors is allowed, and this bug needs to be fixed.

**Comment by FroMage** [comment]
Fixed.

**Comment by lucaswerkmeister** [comment]
Thanks!
