### ISSUE TITLE
Problem with attribute inside an interface when loaded by the model loader

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#2249]
The following code compiles and runs well when both classes are in the same module / project :
```ceylon 
shared interface InterfaceWithInitializedAttribute {
    shared variable formal String? internalValue;
    shared default String attribute {
        if (exists a=internalValue) {
            return a;
        } else {
            internalValue = initialValue();
            assert(exists n=internalValue);
            return n;
        }
    }
    assign attribute {
        internalValue = attribute;
    }
    shared formal String initialValue();
}

shared class ClassWithInitializedAttribute() satisfies InterfaceWithInitializedAttribute {
    shared actual String initialValue() => "Initial";
    shared actual variable String? internalValue = null;
}

shared void run() {
    print(ClassWithInitializedAttribute().attribute);
}
```

However, when the `InterfaceWithInitializedAttribute` is defined in another module, and loaded from a CAR binary archive by the model loader, I get this backend error in `ClassWithInitializedAttribute`:
`ClassWithInitializedAttribute is not abstract and does not override abstract method setAttribute(java.lang.String) in InterfaceWithInitializedAttribute`

**Comment by davidfestal** [comment]
This currently blocks my pending work on branch https://github.com/ceylon/ceylon-ide-eclipse/tree/wip-abstraction-ExtractValueRefactoring

**Comment by quintesse** [comment]
@davidfestal I fixed this as best as I could so you can at least continue working.

@FroMage Please take a look at this because my fix doesn't feel good at all. The weird thing is that the `attribute` shows up as a `JavaBeanValue` instead of a `Getter` and a `Setter` which was the reason why the setter didn't get generated.

**Comment by davidfestal** [comment]
Thanks @quintesse for fixing it so fast !

**Comment by FroMage** [comment]
I don't understand why you added another `Value`, so we have two now?

**Comment by quintesse** [comment]
I copied that from the initialization performed for setters in the typechecker, see: https://github.com/ceylon/ceylon-spec/blob/master/src/com/redhat/ceylon/compiler/typechecker/analyzer/DeclarationVisitor.java#L1280

**Comment by quintesse** [comment]
The parameter created in the ModelLoader just seemed to missing information so I went looking for how to "properly" initialize it and I found that code, I copied it and things started working. The reason *why* it needs that Value is unknown to me.

**Comment by FroMage** [comment]
Mmm, that method from `DeclarationVisitor` looks weird to me. Oh, I suppose that's defining the _implicit_ setter parameter. But then why is it added not to the setter but to its container? @gavinking?

**Comment by quintesse** [comment]
Btw, if it wasn't clear the new Value is for the Parameter of the Setter, it is not a copy of the original Value (it's not the Setter's getGetter())

**Comment by FroMage** [comment]
@quintesse in general before fixing a model loader bug you should add a test to the model loader tests, and make sure it fails. If it doesn't, you need to fix the model loader tests because it's missing things to check.

**Comment by quintesse** [comment]
I have no idea what you're talking about, I added a test, didn't I?

**Comment by FroMage** [comment]
In the model loader tests ;)

**Comment by FroMage** [comment]
Which is where we compare the model from source and from binaries.

**Comment by gavinking** [comment]
> But then why is it added not to the setter but to its container?

Because its scope is the setter?

**Comment by FroMage** [comment]
But apparently it's added to the container of the setter, no?

**Comment by gavinking** [comment]
eh?

**Comment by FroMage** [comment]
```java
  public void visit(Tree.AttributeSetterDefinition that) {
//...
        Value v = new Value();
//...
        Scope sc = getContainer(that); // container of the setter
        sc.addMember(v); // adding the Value of the parameter to the container of the setter
```

**Comment by FroMage** [comment]
Bah, whatever. This works, good enough for me.
