### ISSUE TITLE
constructor delegation does not work for two delegations in a row

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2256]
This code
```ceylon
shared class Foo {
		
		shared new (Integer i){}
		
		shared new init() extends Foo(42){}
		
		shared new init2() extends init(){}
		
}
```
makes the compiler *super angry*

`no suitable constructor found for Foo(foo.Foo.$delegation$)
    constructor foo.Foo.Foo(foo.Foo.init2_) is not applicable
      (actual argument foo.Foo.$delegation$ cannot be converted to foo.Foo.init2_ by method invocation conversion)
    constructor foo.Foo.Foo(foo.Foo.init_) is not applicable
      (actual argument foo.Foo.$delegation$ cannot be converted to foo.Foo.init_ by method invocation conversion)
    constructor foo.Foo.Foo(foo.Foo.init$delegation$_) is not applicable
      (actual argument foo.Foo.$delegation$ cannot be converted to foo.Foo.init$delegation$_ by method invocation conversion)
    constructor foo.Foo.Foo(long) is not applicable
      (actual argument foo.Foo.$delegation$ cannot be converted to long by method invocation conversion)
    constructor foo.Foo.Foo(foo.Foo.$delegation$,long) is not applicable
      (actual and formal argument lists differ in length)`

Note : keep the `Integer i` parameter, else the code compiles.

**Comment by FroMage** [comment]
Yeah, you probably have the open-source license. With that you can only do one level lof delegation. You need the "pro" license for up to three levels of delegation. You can wire me the money for the license and I'll send you one.

**Comment by sgalles** [comment]
Uhm...Ok it makes sense. Do you have a usage-based license though ? I
shouldn't pay when I'm not calling my 2-level constructor at runtime.

**Comment by FroMage** [comment]
Sure, we have a pay-per-use license too, where each first delegation is 0.4€ per use, and then 0.1€ per additional level. That license comes with 30 free first delegations per month.

**Comment by sgalles** [comment]
Ah ! Thank you. This license scheme is complicated enough so that I do not
understand what I'm paying and now it's painless. Appreciated.

**Comment by FroMage** [comment]
And we have a bundle offer with telco companies that if you guy that license and a new smartphone contract you get lubricant for free.

**Comment by sgalles** [comment]
You add a copy of  "Stockholm Syndrome for Dummies" to the bundle and I
think we have a deal !

**Comment by FroMage** [comment]
OK done. I'm waiting for your money now ;)
