### ISSUE TITLE
NPE for import of value constructor

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2262]
When this code is compiled
```ceylon
import foo{
	Foo {bar}
}

class Foo{
	shared new bar{}
}

shared void run(){
	Foo f = bar;
	print(f);
}
```
`The Ceylon Java backend compilation failed with 1 malformed Javac tree cases with a throwable : java.lang.NullPointerException`
`cannot find symbol
  symbol:   method getFoo$bar()
  location: class foo.run_`

**Comment by FroMage** [comment]
Fixed
