### ISSUE TITLE
Identifier case mangled

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-compiler#2264]
Hi,

as aired on ceylon-users I have

shared object mathHelpers {   
    shared Float _M_PI = 3.14159265359;
}

... (same file)
 2 * mathHelpers._M_PI

// other  (test) project

 assertEquals (..., mathHelpers._m_pi);

In fact, _M_PI would not work, and the IDE completes to small type.

So, this might be a model loading/serialization problem. An oddity is that I cannot follow to the definition of _m_pi (F3 key in eclipse) whereas in non-mangled cases in the same (test) project it works fine.

**Comment by simonthum** [comment]
(FWIW I know Pi is actually lower case, I just decreased the effort to convert from C this way)

**Comment by FroMage** [comment]
Done. Turns out we considered `_` to be non-lowercase in the model loader (while the parser did consider it lowercase). AND we had a bug with getter/setter names if the attribute name started with a lowercase then immediately an uppercase.

**Comment by simonthum** [comment]
Thanks, nice catch(es)!

**Comment by simonthum** [comment]
While you're at it, maybe the NamingBase fix indicates that this code should be common to loader and compiler.

**Comment by FroMage** [comment]
It is common.

**Comment by simonthum** [comment]
Sure, the loader is common and the compiler will see names that went through getJavaBeanName(). 

Yet is seems the root issue is that there is an understanding the underscore is lowercase in ceylon, which was omitted here. So it's not common in the sense that the compiler was free to use another definition.
