### ISSUE TITLE
“Error: possible loss of precision” for if condition involving JInteger

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2271]
```ceylon
import java.lang { JInteger=Integer }
void t() {
    JInteger? ji = null;
    if (exists i = ji?.intValue(), true) {}
    else {}
}
```
> source/tmp/run.ceylon:4: error: possible loss of precision
```ceylon
    if (exists i = ji?.intValue(), true) {}
               ^
```
  required: int
  found:    long

The error disappears if there is only a single condition (i. e., you remove the `, true`) or if the `else` branch is missing.

As always, [generated code](https://gist.github.com/lucaswerkmeister/b9e023e6274569de323e), `@noanno`’d.

Looking at the generated code, the problem is:
```java
final int i$3;
if ((i$1 = (
    // …
} else {
    i$3 = 0L;
}
```
The compiler emits an `int i$3` field for `i`’s value within the `if` body.
Then, in the `else` part of the first generated test, it has to initialize that variable with something, and attempts to do so with a `0L` value, which doesn’t fit.

If there is only a single condition, or if there is no `else` branch, then the compiler can skip the `$ceylontmp$if$0` step and only emit `int i$3` within the `if` branch, where no one has to initialize it with `0L`, so the error doesn’t happen.

**Comment by jvasileff** [comment]
Seems like `i$3` should be a `long`. For example:

```ceylon
import java.lang { JInteger=Integer }

@noanno
shared void run() {
    JInteger? ji = JInteger(2);
    if (exists i = ji?.intValue(), true) {
        print(i^31); // -2147483648
        print(2^31); //  2147483648
        assert(i^30 == 2^30); // ok
        assert(i^31 == 2^31); // boom
    }
}
```

**Comment by lucaswerkmeister** [comment]
Thanks @tombentley! Now to fix the same bug for `JShort` :P
