### ISSUE TITLE
NPE `MethodOrValueReferenceVisitor` in IDE

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2274]
This happens in the IDE only with this broken code
```ceylon
shared class Foo{
	shared new init();
	shared new () extends init(){} 
}
```
`the 'MethodOrValueReferenceVisitor' caused an exception visiting a 'ClassDefinition' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.java.loader.MethodOrValueReferenceVisitor.visit(MethodOrValueReferenceVisitor.java:279)'`

**Comment by quintesse** [comment]
Btw, in an updated IDE the line is actually 284: `the 'MethodOrValueReferenceVisitor' caused an exception visiting a 'ClassDefinition' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.java.loader.MethodOrValueReferenceVisitor.visit(MethodOrValueReferenceVisitor.java:284)'`

**Comment by tombentley** [comment]
Fixing the NPE reveals a problem with error recovery with delegating constructors: If we don't generate the `$delegation$` constructor (because the corresponding constructor has errors) then constructors which delegate to it get missing symbol errors in javac.

**Comment by quintesse** [comment]
Btw @tombentley , in the CLI compiler when a file has errors like that it gets ignored completely, it seems the IDE doesn't do that, might that be the cause for those missing symbol errors or is that unrelated?

**Comment by tombentley** [comment]
Yeah, I noticed that too @quintesse and I wasn't sure why the two differ.

**Comment by quintesse** [comment]
Well the IDE re-implements the highest level of the compiler itself (probably because it inserts some stuff of its own), so perhaps @davidfestal should be in on this issue to see what he can say about it.

**Comment by tombentley** [comment]
Well I've fixed this and made error recovery with delegating constructors a little bit better. I'm still not sure how/why the IDE continues compiling even when faced with syntax errors (the CLI pretty much gives up on those, IIRC).
