### ISSUE TITLE
CCE working with Integer|Float

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2277]
I guess this is valid code:

```ceylon
    variable Integer|Float iof = 1.0;
    iof += 1;
```

```
ceylon run: ceylon.language.Integer cannot be cast to ceylon.language.Float
java.lang.ClassCastException: ceylon.language.Integer cannot be cast to ceylon.language.Float
	at ceylon.language.Float.plus(Float.java:14)
```

Similar with:

```ceylon
    variable Integer|Float iof = 1;
    iof += 1.0;
```

and:

```ceylon
    variable Integer|Float iof = 1;
    iof += iof;
    
    /*
     Method plus in interface ceylon.language.Summable<Other> cannot be applied to given types;
     required: ceylon.language.Summable
     found: java.lang.Object
     reason: actual argument java.lang.Object cannot be converted to ceylon.language.Summable by method invocation conversion
     */
```

**Comment by jvasileff** [comment]
Maybe this one is a spec bug, since the static type of `Integer|Float` is neither `Integer` nor `Float`.

> Arithmetic operators automatically widen from Integer to Float when necessary. If one operand expression is of static type Integer, and the other is of type Float, the operand of type Integer is widened to a Float in order to make the operator expression well-typed. Widening is performed by evaluating the attribute float defined by Integer.

@gavinking ?

**Comment by gavinking** [comment]
I would say this is a type checker bug, yeah.

**Comment by FroMage** [comment]
Moved to https://github.com/ceylon/ceylon-spec/issues/1406 then.
