### ISSUE TITLE
Terminal width not respected

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2296]
`tput cols` gives 174 in my terminal, but not when called by the `ceylon` script where it gives 80. `stty cols` works, so I'll replace it with that.

**Comment by lucaswerkmeister** [comment]
Are you piping anything into the script? I think we should try to find out why it doesn’t work for you (works here).

**Comment by FroMage** [comment]
No. Apparently it causes issues for other people too.

**Comment by FroMage** [comment]
Could this be related?

```
$ ls -lsa /bin/sh
0 lrwxrwxrwx 1 root root 4 Jan 31  2015 /bin/sh -> dash
```

**Comment by lucaswerkmeister** [comment]
Hm, possibly. My `sh` is provided by `bash`.

**Comment by quintesse** [comment]
Yes finally! Thanks Stef.
