### ISSUE TITLE
Print progress during compilation

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2297]
So we know what the hell is happening, with `--progress` option (off by default).

**Comment by lucaswerkmeister** [comment]
:+1:

**Comment by FroMage** [comment]
Done!

**Comment by quintesse** [comment]
Nice job!

Btw, could this perhaps be extended to provide cancellation?
See https://github.com/ceylon/ceylon-ide-eclipse/issues/1202

**Comment by FroMage** [comment]
Sure, canceling is supported, just press `Ctrl-c` ;)

**Comment by quintesse** [comment]
Did you follow the link I provided? It's for the IDE ;)
