### ISSUE TITLE
ceylon doc: consider listing "most refined" inherited members

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2300]
Currently, "Inherited Attributes" and "Inherited Methods" list the least refined declaration of inherited members, making it difficult to find documentation for the "best" version of a type's attributes and methods.

For example, in the `Array` [docs](http://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/Array.type.html), "Inherited Attributes" includes `Correspondence.keys` rather than the more useful and accurate `List.keys`.

Users of a type may miss out on useful functionality. Implementors of a type may miss documented requirements added by a refinement.

Note: there are also some irregularities, such as `Category.contains()` being listed redundantly (`contains` is also refined by `Array`), and `Object.equals()` and `List.equals()` both being listed. But I'll hold off on opening another issue until the desired behavior is made clear.

**Comment by FroMage** [comment]
@thradec would you have time for that?

**Comment by thradec** [comment]
I changed it to same approach as javadoc use, so now there are listed all inherited members from all superclasses/interfaces. Please reopen, if you don't like it ;-).

**Comment by jvasileff** [comment]
Looks great, thanks!
