### ISSUE TITLE
ceylon.interop.java javaBooleanArray and other functions herd doc errors

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2307]
https://modules.ceylon-lang.org/repo/1/ceylon/interop/java/1.1.0/module-doc/api/index.html#javaBooleanArray

In doc
```ceylon
shared BooleanArray javaBooleanArray(Array<Boolean>|Array<Boolean> array)
```

should be
```ceylon
shared BooleanArray javaBooleanArray(Array<Boolean>|Array<Bool> array)
```

Some other functions in ceylon.interop.java have same error

Originally by @NikNik77771 on https://github.com/ceylon/ceylon-sdk/issues/417

**Comment by FroMage** [comment]
I support it has to do with aliases. Perhaps already fixed in 1.2, we need to check.

**Comment by thradec** [comment]
closing, should be done

**Comment by FroMage** [comment]
Wow, that was fast :) Thanks!
