### ISSUE TITLE
unused partial constructor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2317]
For:

```ceylon
class Org {
    shared String name;
    abstract new partial() {}
    shared new forName(String name) {
        this.name = name;
    }
}
```

I get:

    variable name might not have been initialized

**Comment by tombentley** [comment]
Interesting. An abstract constructor that's never delegated to. My gut response it to simply omit it from the generated class file, but then it wouldn't exist in the metamodel, so I guess I need to have it `throw`

**Comment by tombentley** [comment]
*What* should it throw though? It's a compiler-level error, I suppose, so maybe we need some sort of `UninstantiableConstructorError` ?

**Comment by gavinking** [comment]
Thanks.
