### ISSUE TITLE
Fix dynamic interfaces?

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2326]
Apparently in #1679 we added support for `dynamic` interfaces on the JVM, but in ceylon/ceylon-spec@2d0c577 we moved the unsupported on this backend error checking for dynamic to the TC.

So if we really do need to support dynamic on the JVM (and not one but @gavinking seems to understand why we do), then we need to fix this.

**Comment by tombentley** [comment]
What I didn't mention is that the errors reported by the TC now result in the `dynamic` interfaces not being generated. Which is why there's a "bug". 

But I think @quintesse has it right when he says that a `dynamic` interface should be `native("js")`

**Comment by FroMage** [comment]
So what do we have to do here?

**Comment by tombentley** [comment]
The best thing to do would be to only allow `dynamic` in a `native(<backends that support dynamic>)`. In such a way that JVM compiler doesn't need to emit anything for `dynamic` interfaces. We did that before just for model loading purposes in the IDE (with both backends enabled) I think.

**Comment by quintesse** [comment]
Indeed, but @gavinking doesn't seem to like that idea although to me it seems obvious (the code *has* to be native).
Btw the entire reason for supporting dynamic interfaces is so the JS compiler won't mess up *in the IDE* because the IDE uses the JVM model loader for everything, even JS.

**Comment by FroMage** [comment]
So what do we do? ATM dynamic interfaces generate an error from the typechecker.

**Comment by tombentley** [comment]
Well the old workaround was the have the JVM compiler emit an empty interface of a `dynamic` interface with a model annotation to say it was dynamic. That kept the model loader sweet. But now that the TC does the "dnamic is not supported on the JVM" error, the backend doesn't know that it should compile the interface in spite of the error.

So to re-enable the old hackish way we'd need an error code on the error added by the TC, then the backend can arrange to ignore that error when decided whether to generate code.

It just seems wrong to me to go to those lengths of hack when there's a more right seeming solution.

**Comment by quintesse** [comment]
Well I don't think *we* (as in the compiler backend) don't have to do anything. Right now there's no obvious (and quick) way to really implement something that resembles "dynamic" on the JVM and in any case this dynamic interface thing is all a hack for the IDE.

So in my opinion the only thing that needs to be done is that @gavinking adds an exception to the dynamic checking in the TC where he allows it for interfaces on the JVM.

**Comment by quintesse** [comment]
Btw, the *real* solution would be for the IDE to start using the JS Model Loader for JS code, but that's unfortunately not as easy as it sounds.

(Technical explanation, skip if not interested: The TC is only run once over a file that could contain code for several backends, even if you use a "merged model loader", something that @davidfestal and I have talked about, a model loader that wraps both a JVM and a JS model loader and can look up in both, it won't be enough because it might still choose the wrong one. Instead it would need to know for which backend the lookup is done and then choose the corresponding model loader, that's something that is not possible right now)

**Comment by FroMage** [comment]
So we have to reallow it for JVM even though we know it won't work?

**Comment by quintesse** [comment]
Without breaking the IDE or doing a lot of work to change how the TC deals with model loaders I don't think so. @davidfestal might have an idea how much work it would be for the IDE to use a "merged loader" but I don't think it's trivial. And then there are still the changes to the TC to consider. So the quick-and-dirty way would be to continue to do what we did so far, which is to allow it (for now).

**Comment by FroMage** [comment]
Done.
