### ISSUE TITLE
support ReferenceDeclaration

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2328]
I think this is a regression because I think it was working before. Related to ceylon/ceylon.language/issues/681.

```ceylon
String name = "Gavin";
ReferenceDeclaration referenceDeclaration = `value name`;
```

I get:

```
Incompatible types
  required: ceylon.language.meta.declaration.ReferenceDeclaration
  found:    ceylon.language.meta.declaration.ValueDeclaration
```

Both the typechecker and the language module know that this is supposed to be a `ReferenceDeclaration` here, so my first guess is that the problem is in the compiler.

**Comment by FroMage** [comment]
Well, it was done for members, but not toplevels.

**Comment by FroMage** [comment]
Done.
