### ISSUE TITLE
Invalid "missing return statement"

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2331]
I'm trying to use Java overloads and I noticed this strange error:

```
import com.redhat.ceylon.compiler.typechecker.tree {
    Visitor,
    Tree
}

class InterveningVisitor() extends Visitor() {
    shared actual default void visit(Tree.AssignmentOp ao) {
        super.visit(ao);
    }
    shared actual default void visit(Tree.CompilationUnit ao) {
        super.visit(ao);
    }
}

class ChildVisitor() extends InterveningVisitor() {
    shared actual void visit(Tree.UnaryOperatorExpression uoe) {
        //      ^
        //      error: Missing return statement
        super.visit(uoe);
    }
}
```

(the module needs to `import com.redhat.ceylon.typechecker "1.1.1";`)

**Comment by FroMage** [comment]
So this is again due to overloading indeed. Problem is that because `getDirectMember` does not respect the hierarchy and the signature I can only make this work for obviously overloaded declarations, and it will still fail with generics. Still, should be good enough for you/now.

**Comment by FroMage** [comment]
Fixed.
