### ISSUE TITLE
support flow-typing improvement

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2333]
The backend needs to support the improvement in ceylon/ceylon-spec/issues/891.

An example is:

```ceylon
Integer fun(Integer? int) {
    if (!exists int) {
        return 0;
    }
    return int+1;
}
```

Which currently results in this backend error:

```
Bad operand types for binary operator +
  first type:  ceylon.language.Integer
  second type: long
```

**Comment by quintesse** [comment]
Could you give a small explanation of how you implemented it? Because I intuitively understood the `SyntheticAssert` but you removed and improved it and now it's not as obvious to me how to implement it on the backend.

**Comment by gavinking** [comment]
I used the same strategy I use for narrowing in `else` clauses. I add a `Variable`. In this case the `Variable` gets slotted into block just after the `if` statement, and it gets a special new scope.

**Comment by FroMage** [comment]
OK I'll bite.

**Comment by FroMage** [comment]
Done!

**Comment by gavinking** [comment]
Excellent, thanks :)
