### ISSUE TITLE
Cannot use spread operator to invoke member class

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2335]
This code produces a compile time backend error:

```ceylon
shared class C() {
    shared class D() {}
    value ds = { C() }*.D(); // Cannot find symbol symbol: method D$new$()
    print("done");
}

shared void run() {
    C();
}
```
Similar happens if `C` is an interface, and also if everything is contained within `run`.

**Comment by gavinking** [comment]
Ouch, this is a regression for sure.

**Comment by FroMage** [comment]
No this does not seem to have ever been implemented.

**Comment by FroMage** [comment]
Equally, `opt?.D();` was also never implemented.

**Comment by FroMage** [comment]
Done, both.
