### ISSUE TITLE
deprecation warnings missing

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2342]
When compiling the following code on the CLI, or in the IDE with the Java backend enabled, I get no deprecation warning:

```ceylon
shared void run() => arrayOfSize(1, true);
```

**Comment by gavinking** [comment]
It appears that the deprecated attribute is simply being dropped by the model loader. That's a regression.

**Comment by tombentley** [comment]
Fixed

**Comment by gavinking** [comment]
Thanks.
