### ISSUE TITLE
named arg invocation where T is Iterable

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2349]
`[]` is not used for non-defaulted `Iterable` arguments when necessary for invocations using named argument lists when the `Iterable` parameter's declaration is not constrained to be of an `Iterable` type.

```ceylon
class C<T>(T t) {}
value c = C<{Integer*}> { }; // compiler bug: compiler bug: missing argument, and parameter is not defaulted
```
and
```ceylon
identity<{Integer*}> { }; // same error
```

**Comment by FroMage** [comment]
@gavinking is this really blessed by the spec?

**Comment by lucaswerkmeister** [comment]
My 2cts: The [spec](http://ceylon-lang.org/documentation/1.1/spec/html_single/#namedarguments) says:

> Next, if the parameter list has an unassigned parameter of type exactly `Iterable<T,N>` for some types `T` and `N`, then an iterable enumeration expression, as defined in §6.6.12 Iterable and tuple enumeration, is formed from the ordinary list of arguments, and assigned to that parameter.

Not sure if “exact type (equality)” does type parameter substitution, but I’d guess it does, so this is probably blessed.

**Comment by FroMage** [comment]
OK, doesn't sound crazy anyway. Thanks.

**Comment by gavinking** [comment]
I would say that the spec is unclear on this point: it doesn't seem to say clearly that this is for the *realization* of the parameter list.

But yes, I would say that it would be better if the typechecker continues to allow this.
