### ISSUE TITLE
Generate a class for native headers

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-compiler#2356]
Right now native headers have no presence in the generated output which means we lose important information about the structure of `native` declarations which causes problems in certain situations (see https://github.com/ceylon/ceylon-ide-eclipse/issues/1531 for example)

**Comment by tombentley** [comment]
This is necessary because the IDE uses the java model loader even when compiling js...?

Are you going to generate a .class or just annotate the classes which we do generate?

**Comment by davidfestal** [comment]
Or could'nt we simply annotate the classes we generate and have the model loader use this annotation to create both the native header and the native implementation ?

**Comment by quintesse** [comment]
I think annotating the existing class isn't enough, they don't need to be 100% the same and in that case the model loader code would get more complex with all kinds of corner cases ,so I prefer to try the extra class first

**Comment by tombentley** [comment]
Its more bloat, that all :-(

**Comment by quintesse** [comment]
Ok, after thinking about it some more you guys convinced me that perhaps some annotation might the better solution. I'll see if I can make that work.

**Comment by quintesse** [comment]
Reverted all this for now because even though the tests pass all kinds of strange things seem to be happening in the IDE.

**Comment by quintesse** [comment]
@davidfestal can you take a look at this branch to see if it gives trouble for the IDE?

**Comment by davidfestal** [comment]
@quintesse : the good new is : it works fully in the IDE visibly.

**Comment by quintesse** [comment]
Ok, done, closing.
