### ISSUE TITLE
ceylon info does not find modules in Herd

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2379]
```
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld
Module com.acme.helloworld not found in the following repositories:
    /Users/gavin/ceylon-dist/dist/repo
    /Users/gavin/ceylon-web-ide-backend/modules
    JDK modules repository
    /Users/gavin/ceylon-web-ide-backend/modules
    /Users/gavin/.ceylon/repo
    /Users/gavin/.ceylon/cache
    http://modules.ceylon-lang.org/repo/1
    [Maven] Aether

Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld/1.0.0
Module com.acme.helloworld not found in the following repositories:
    /Users/gavin/ceylon-dist/dist/repo
    /Users/gavin/ceylon-web-ide-backend/modules
    JDK modules repository
    /Users/gavin/ceylon-web-ide-backend/modules
    /Users/gavin/.ceylon/repo
    /Users/gavin/.ceylon/cache
    http://modules.ceylon-lang.org/repo/1
    [Maven] Aether
```

**Comment by quintesse** [comment]
Is this the example that's distributed with dist?

**Comment by quintesse** [comment]
Ah no it's something in `ceylon-web-ide-backend/modules`?

Anyway, is the module available in any of those paths?

**Comment by gavinking** [comment]
It's in Herd and nowhere else.

**Comment by quintesse** [comment]
Aaah! Well then I know what's up: you need to add `--show-incompatible` , by default `ceylon info` only returns results you can actually use with your current install.

**Comment by gavinking** [comment]
OK.

**Comment by gavinking** [comment]
@quintesse Look, reflecting on this, it really seems to me like the default for `--show-incompatible` is wrong. I mean, if I ask for info on a specific version of a specific module, `com.acme.helloworld/1.0.0`, and it lies to me and pretends not to find it!

I'm perfectly fine with the idea of emphasizing in the info that this is an incompatible module, but pretending it doesn't exist is just confusing to the user!

**Comment by gavinking** [comment]
@quintesse @FroMage how about we print out incompatible versions, but annotate them with a warning `!` ... WDYT?

**Comment by FroMage** [comment]
Well, the same code is used by the IDE, where you definitly don't want to import them as it would give you an error.

**Comment by quintesse** [comment]
Really, I'm not sure why we would do this, the list would just get longer and longer with 99% of the information being useless, see for example the output for `ceylon info ceylon.math`:

```
Showing versions for module 'ceylon.math'
    0.1 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.2 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.3.1 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.3.2 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.4 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.5 - /home/ceylon/.ceylon/cache
    0.6 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    0.6.1 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    1.0.0 - The Herd (http://modules.ceylon-lang.org/repo/1) *
    1.1.0 - /home/ceylon/.ceylon/repo
    1.2.0 - /home/ceylon/.ceylon/repo
```

With the list now showing the repo it comes from it's already much more crowded too, adding `not compatible` will make it even more so. Instead of just getting:

```
    1.2.0 - /home/ceylon/.ceylon/repo
```

By default.

Now maybe we could change the default for when you give a version as well, the idea being that if you're being so specific it's probably because you have reason to. And then add the warning that it's incompatible

**Comment by quintesse** [comment]
Ok, implemented that if you specify the version it will show incompatible modules as well, see how you like it @gavinking

**Comment by gavinking** [comment]
Well at the very least, I think the message needs to be changed:

```ceylon
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld
Module com.acme.helloworld not found in the following repositories:
    /Users/gavin/ceylon-dist/dist/repo
    /Users/gavin/ceylon-web-ide-backend/modules
    JDK modules repository
    /Users/gavin/ceylon-web-ide-backend/modules
    /Users/gavin/.ceylon/repo
    /Users/gavin/.ceylon/cache
    http://modules.ceylon-lang.org/repo/1
    [Maven] Aether
```

`Module com.acme.helloworld not found in the following repositories` is simply misleading.

**Comment by quintesse** [comment]
Ok, so I changed it that it also does it when no version is given. So what happens now is that it will first look for *compatible* versions and only when that fails to return a result will it try again but now allowing *incompatible* versions. How about that?

**Comment by quintesse** [comment]
Although probably now I need to add an option `--show-compatible-only` or something. Ah well.

**Comment by gavinking** [comment]
That sounds a lot better.

**Comment by gavinking** [comment]
Well this is still all a bit weird:

```
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld
Showing versions for module 'com.acme.helloworld'
    1.0.0 - The Herd (http://modules.ceylon-lang.org/repo/1) [incompatible] [not downloaded]
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon run com.acme.helloworld/1.0.0
ceylon run: Could not find toplevel function 'com.acme.helloworld.run'.
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld
Showing versions for module 'com.acme.helloworld'
    1.0.0 - /Users/gavin/.ceylon/cache
Gavins-New-MacBook-Pro:ceylon-web-ide-backend gavin$ ceylon info com.acme.helloworld/1.0.0
Name:        com.acme.helloworld
Version:     1.0.0
Available:   On local system
Origin:      /Users/gavin/.ceylon/cache
```

So:

- when it was on Herd, it was `[incompatible]`
- but `ceylon run` was perfectly happy to download it and try and run it anyway
- and then, now that it's in my cache, it's not marked `[incompatible]` anymore

That all feels pretty inconsistent.

**Comment by quintesse** [comment]
Well that's not the fault of the info tool, it gives you the info it can give:

 - It shows the info the Herd gives it (being incompatible for example)
 - "run" downloads it, nothing it can do about that
 - The helloworld module is so tremendously outdated (m2!) that it's not able to read any of the meta information, so it shows you what it can (very little)

**Comment by quintesse** [comment]
We can ready all the info from modules from version 1.0 upwards of course, so I'd suggest to remove any artifacts from the Herd that are too old.

**Comment by gavinking** [comment]
OK. Is it a bug in `ceylon run` that it downloads stuff it can't run?

**Comment by quintesse** [comment]
No, it 's not so much a bug as a consequence of the kinds of repositories it has to deal with. The Herd gives a lot of information but a Maven or plain HTTP server wouldn't and "run" is still able to download and run those. It could perhaps do a query first to see if there's any information available for the thing it's going to download, but I guess that would just slow down things in the 99% of the normal cases.
That it doesn't give a better error about compatibility has again to do with the fact it's such an old module (it probably treats it as a legacy JAR file, so the only error you get is about the missing function).

**Comment by gavinking** [comment]
Can't it give an error in the case that:

1. it is a Ceylon module, and
2. there is no version info.

I don't care if the error happens *after* downloading the module, FTR.

**Comment by quintesse** [comment]
It probably *could*, don't know if there are use-cases where it shouldn't. Any ideas @FroMage @tombentley ? (TL;DR Should the run tool give an error if we tell it to run a module which exists locally but for which it can't retrieve the module descriptor information)

**Comment by gavinking** [comment]
I mean, right now it fails with `Could not find toplevel function 'com.acme.helloworld.run'` or worse (BC errors).

It seems to me it would be much better if it failed with `Module 'com.acme.helloworld.run' is not compatible with this version of the Ceylon runtime`.

**Comment by quintesse** [comment]
Sure, open a new issue for it will you?
