### ISSUE TITLE
constructor throwing exception

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2384]
This seems like it must be a regression.

```ceylon
class XX {
    shared new() {
        throw Exception();
    }
    shared new foo() {}
    String it = "";
}
```

I get:

    unreachable statement

Same for this:

```ceylon
class XX {
    shared new() {
        assert (false);
    }
    shared new foo() {}
    String it = "";
}
```

**Comment by tombentley** [comment]
Because of the semantics we have to `return` in a constructor (we just exit that constructor) I need a way to distinguish constructor bodies that definitely return via `return` from those which definitely return via `throw` or `assert(false)`.

**Comment by tombentley** [comment]
@gavinking see my above comment. I can't do this without knowing whether the constructor `Tree.Block` returns via `return` or abnormally. Isn't that something the `ControlFlowVisitor` could provide?

**Comment by gavinking** [comment]
I'm not sure. I would have to look at the code.

**Comment by gavinking** [comment]
@tombentley and what behavior do you expect if some branches exit with `return` and some with `throw`?

**Comment by gavinking** [comment]
It seems like the case you want to detect is the case where *every* branch results in a thrown exception.

**Comment by gavinking** [comment]
@tombentley I think you should just create a `Visitor` that searches the body of the constructor for `return` statements. That's going to be a lot simpler. What I mean is:

    class V extends Visitor {
        private boolean found = false;
        @Override
        public void visit(Return that) {
            super.visit(that);
            found = true;
        }
        @Override
        public void visit(Declaration that) {}
    }

**Comment by tombentley** [comment]
I had to use a variation of the `ControlFlowVisitor` to handle things like 

    if (true) { throw; }

it's a bit more copy and paste than is ideal, but it seems to work.

**Comment by gavinking** [comment]
OK, thanks Tom.
