### ISSUE TITLE
`ceylon doc ceylon.language` fails

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2393]
```
atlantis stephane 19:42 ceylon.language $ ../ceylon-dist/dist/bin/ceylon doc ceylon.language
ceylon doc: Assertion failed: language package is null

Usage:
ceylon doc [--browse] [--cacherep=<url>] [--cwd=<dir>] [--doc=<dirs>...] [--encoding=<encoding>] [--footer=<footer>] [--header=<header>] [--ignore-broken-link] [--ignore-missing-doc] [--ignore-missing-throws] [--link=<dir-or-url>...] [--maven-
           overrides=<url>] [--no-default-repositories] [--non-shared] [--offline] [--out=<url>] [--overrides=<url>] [--pass=<secret>] [--rep=<url>...] [--source=<dirs>...] [--source-code] [--src=<dir>...] [--sysrep=<url>] [--timeout=<seconds>] [--
           user=<name>] [--verbose[=<flags>]] [--] [<modules...>]

Run 'ceylon help doc' for more help
```

**Comment by tombentley** [comment]
I think this is a problem with cmr, rather than the tool itself. AFAICS the tool makes a bunch of requests to CMR to do the copying, each for several suffixes, and the CMR just copies the first one of each.

It's a bit difficult to say whether that's the CMRs fault, or the tools, because the lack of documentation in the CMR means I've no idea what contract it's providing.

**Comment by FroMage** [comment]
Well, we can always make one call per suffix?

**Comment by FroMage** [comment]
Oh, were you perhaps commenting on the `ceylon copy` issue?

**Comment by tombentley** [comment]
Yes, I think that will work, for this issue at least. 

But there's still something wrong. At the least the contract for `RepositoryManager.getArtifactResults(ArtifactContext)` needs to be defined (in particular the case of a whole bunch of suffixes in the passed `ArtifactContext`), but assuming it should be returning an `ArtifactResult` for each suffix that actually exists in the configured repositories then it's broken. @quintesse is the expert in all this, of course, but I think he's busy right now.

**Comment by tombentley** [comment]
Yes, all these comments of mine are on the wrong issue, meant for #2394

**Comment by FroMage** [comment]
So this issue is about not finding the language source files because they're in `src` and not `source`. I'll make sure we get more useful error messages.

**Comment by tombentley** [comment]
If it wouldn't ruin `git blame` I'd suggest we also rename the directory to `source`.

**Comment by FroMage** [comment]
Aw please stop using that issue man!!! ;)

**Comment by FroMage** [comment]
Now fixed.
