### ISSUE TITLE
Incompatible types: j.l.String vs c.l.String

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2397]
The following code results in a backend error:

```ceylon
import java.lang {
    ObjectArray
}
void run(ObjectArray<String> strings) {
    
    for (string in strings.iterable) {
        
    }
}
```

```
source/mymodule/run.ceylon:6: error: incompatible types
    for (string in strings.iterable) {
                                     ^
  required: java.lang.String
  found:    ceylon.language.String
```

**Comment by lucaswerkmeister** [comment]
Generated code: https://gist.github.com/lucaswerkmeister/78364384db3f01ad62c1

**Comment by lucaswerkmeister** [comment]
@tombentley isn’t this fixed by 55da9feb4a47d7449cba7a20b13a9d4f5c77c7c9? At least I can’t reproduce this anymore.

**Comment by tombentley** [comment]
Yes, sorry forgot it wasn't an auto-closing comment.

**Comment by lucaswerkmeister** [comment]
No problem :) and hey, that was the last 1.2 bug in the compiler!
