### ISSUE TITLE
Type-safe Metamodel example fails

### ISSUE THREAD

**Issue by javalama** [ceylon/ceylon-compiler#2398]
Using 1.2 zip-distro pasted on gitter today...

I took the metamodel example from http://trybeta.ceylon-lang.org/ and wrapped it in a function. Compiled fine, but at runtime I get: 

> ceylon.language::List.Element
> ceylon run: Too many type arguments provided: 1, but only accepts 0
> ceylon.language.meta.model.TypeApplicationException "Too many type arguments provided: 1, but 
> only accepts 0" at 
> com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.checkTypeArguments(Metamodel.java:1570)

**Comment by FroMage** [comment]
Turns out the sample was invalid ;)
