### ISSUE TITLE
Ugly index

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2400]
If you look at https://modules.ceylon-lang.org/modules/ceylon.language/1.2.0/doc you will see `<h3>` text and wiki syntax links and other markdown syntax. Presumably we just truncate the markdown text prior to processing it for inclusion in the index. We should do a better job, right now it looks ugly.

**Comment by gavinking** [comment]
FTR, @tombentley means this page, I think:

<https://modules.ceylon-lang.org/repo/1/ceylon/language/1.2.0/module-doc/api/api-index.html>

**Comment by jvasileff** [comment]
Related, I'd be for removing the navigation bar and frames, because:

1. The above link issue
2. Clutter
3. It breaks scrolling on mobile (iOS at least)

**Comment by gavinking** [comment]
> I'd be for removing the navigation bar and frames

+1.

**Comment by FroMage** [comment]
> Related, I'd be for removing the navigation bar and frames, because:

It's not a frame but an `iframe` (not that it matters), but that's a Herd issue, not ceylondoc. And it's only there so you can browse all the way through the docs and still be a single click away from going back to Herd. It's actually a quite useful feature. And you can just click on the bar to remove it.

**Comment by thradec** [comment]
Done, via 2f499b0.

**Comment by tombentley** [comment]
Thanks!
