### ISSUE TITLE
[ant tasks] "ant run" + "ant run-js" makes second one skip compilation when it shouldn't

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-compiler#2402]
1. cd .../samples/helloworld
1. ant run
    * compiles and runs fine)
1. ant run-js
    * thinks it's already compiled, skips compilation and fails to run:
```
compile:
[ceylon-compile] No need to compile com.example.helloworld/1.1.0, it's up to date
[ceylon-compile] Everything's up to date

run:
[ceylon-run] ceylon run: Module com.example.helloworld not found in the following
[ceylon-run] repositories:
[ceylon-run]  /usr/share/ceylon/1.1.0/repo
[ceylon-run]  /usr/share/doc/ceylon-1.1.0/samples/helloworld/modules
[ceylon-run]  /usr/share/doc/ceylon-1.1.0/samples/helloworld/modules
[ceylon-run]  /home/xkr47/.ceylon/cache
[ceylon-run]  http://modules.ceylon-lang.org/repo/1
```

Same occurs if I start over (wipe the modules directory) and run "ant run-js" first (ok) and then "ant run" (fails).

I am using the `ceylon-1.1.0_1.1.0_all.deb` version.

Might be somewhat related to closed bug #537?

**Comment by FroMage** [comment]
Can you try with the 1.2 version?

**Comment by xkr47** [comment]
Works in 1.2

**Comment by FroMage** [comment]
Great news :)
