### ISSUE TITLE
compiler bug: visitor didn't yield any result

### ISSUE THREAD

**Issue by ageery** [ceylon/ceylon-compiler#2434]
The compiler reported a bug when trying to compile the attached project.

[wicket-test.zip](https://github.com/ceylon/ceylon-compiler/files/240943/wicket-test.zip)
[compiler.txt](https://github.com/ceylon/ceylon-compiler/files/240945/compiler.txt)

**Comment by FroMage** [comment]
Thanks for the report, but this repo is closed, I've moved your issue to https://github.com/ceylon/ceylon/issues/6244
